### ISSUE TITLE
Add Khoj to top menu tray in Ubuntu

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#103]
It would be amazing if we had a Khoj utility that showed up in the menu tray at the of the OS menu bar, like below screenshot (for Docker). Simple entrypoints like start/stop/configure would be useful.

![image](https://user-images.githubusercontent.com/65192171/198710028-e5f8ae93-782f-4ef1-9604-77627b840ef6.png)

**Comment by sabaimran** [comment]
Menu tray is now there, but lacks the Icon for some reason.

**Comment by debanjum** [comment]
Verified that the Khoj system tray icon now appears on Ubuntu just fine! 🥳
