### ISSUE TITLE
Allow populating corpus via json or other format.

### ISSUE THREAD

**Issue by khayyamsaleem** [khoj-ai/khoj#149]
Though a file-based corpus is easy for personal, local-machine knowledge-bases, this can be extended to arbitrary knowledge-bases if new entries can be added to the corpus via an API endpoint or using a more generalized text format.

For example, static-site search engines are often building their index using a single file that is easy for a static site generator to render.

**Example**:
I have a hugo site with ~600 markdown files. Some are in the local filesystem, others are pulled using hugo from the internet or other repositories. In the end, they all pass through hugo's renderer, and can be rendered to HTML or JSON or any other file format that I have an created a go template for.

This single-file "dump" is then ingested by a search indexer, like [stork](https://stork-search.net/) or [lunr](https://lunrjs.com/) or [blevesearch](https://blevesearch.com/). Each of these indexers/search-engines can process content in any format either using their library functions or APIs.

This would help to supply content to the model(s) when not necessarily all of it is available on the filesystem or in markdown.

**Comment by debanjum** [comment]
Hey @khayyamsaleem, thanks for providing a use-case and detailed reasoning for the feature request! 🫶🏽
1. Khoj stores the text content indices in a standardized intermediate format as jsonl files
    - For implementation details: See the [architecture diagram](https://github.com/debanjum/khoj#Architecture) and [code](https://github.com/debanjum/khoj/blob/5c0d340970abb422a9ba407c7f8ff9eb2b7f8abb/src/khoj/utils/rawconfig.py#L118)
    - For examples: See `jsonl.gz` file under your `~/.khoj/content/markdown/` directory. E.g `cat ~/.khoj/content/markdown/*.jsonl.gz | zcat | head -n 1`
2. It seems like adding support for external content plugins in #171 should suffice for your hugo website use-case? 
3. The ability to update the index using the API sounds useful for when the khoj server is on a different machine. This capability can be added as a follow-up to #171 

Let me know if that helps with your concerns?

**Comment by debanjum** [comment]
Closing this issue as it's gone stale and the issue ask seems to have been answered
