### ISSUE TITLE
Support custom fields / content metadata in corpus

### ISSUE THREAD

**Issue by khayyamsaleem** [khoj-ai/khoj#150]
An important parameter for the corpus ingestion is the ability to supply "fields" and field-level configuration. This enables capabilities like "boosting," so if khoj found two similarly scored matches, but the `title` field aligned more closely for one match than another, then you could "boost" the title field in the configuration and accordingly that match would rank higher.

I see a strong application for khoj to be used in the context of project or enterprise documentation, and custom field support to tune result ranking would be a huge enabler.

**Comment by debanjum** [comment]
Thanks for the detailing what is required and for what use-case. Khoj uses a search LLM, these do not expose the ability to tune the search rank and building support for such tuning of search ranking is out-of-scope for Khoj, at least for now
