### ISSUE TITLE
Allow pre-loading models

### ISSUE THREAD

**Issue by khayyamsaleem** [khoj-ai/khoj#151]
Right now, the models have to be downloaded at startup if they are not already in the filesystem.

This slows the initial time to API availability, and doesn't work as well in dockerized or network-restricted environments. 

Do you have any guidance around what we could do to preload a model? Could khoj have a CLI option that just wraps around huggingface to download one of the recommended models, so it could be pre-packaged as part of the deployment?

Or can we solve this with documentation for the user to just download the model themselves and place it in an appropriate directory / config.

**Comment by debanjum** [comment]
For now, we can document the option for users to manually download the required search models and put them under `~/.khoj/search/[asymmetric,symmetric,image]`
