### ISSUE TITLE
Periodic index corruption

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#190]
I'm not sure about the exact characterization of when this happens, but it seems to be when I've been running the `khoj` server for a while. It seems like the index frequently becomes corrupted and requires a full regeneration. I would guess that this pertains to the temporal incremental indexing functionality.

**Comment by debanjum** [comment]
Thanks for opening an issue to track this! This is [a known issue](https://github.com/debanjum/khoj#search-starts-giving-wonky-results). But I haven't been able to get to debugging this yet. 

We have a reference test set from #186. Just need to stress test khoj using that (by running search/chat in parallel) and (hopefully) reproduce and fix the index corruption bug

**Comment by jh0274** [comment]
hi! so i ran into a corruption of the .gz markdown embeddings file, here are the logs:

` 📩 Saved current chat session to conversation logs                              
configure.py:229[11:44:53] INFO     📬 Updating content index via Scheduler                                         configure.py:115[11:44:54] INFO     💎 Setting up search for markdown notes                                           
indexer.py:255           INFO     127.0.0.1:59973 - "OPTIONS /api/v1/index/update?force=false&client=obsidian      h11_impl.py:431                    HTTP/1.1" 200
          ERROR    Exception in callback _ProactorBasePipeTransport._call_connection_lost(None) base_events.py:1771                    handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
                    ╭─────────────────── Traceback (most recent call last) ────────────────────╮
                    │ C:\Python311\Lib\asyncio\events.py:80 in _run                            │
                    │                                                                          │
                    │    77 │                                                                  │
                    │    78 │   def _run(self):                                                │
                    │    79 │   │   try:                                                       │
                    │ ❱  80 │   │   │   self._context.run(self._callback, *self._args)         │
                    │    81 │   │   except (SystemExit, KeyboardInterrupt):                    │
                    │    82 │   │   │   raise                                                  │
                    │    83 │   │   except BaseException as exc:                               │
                    │                                                                          │
                    │ C:\Python311\Lib\asyncio\proactor_events.py:165 in _call_connection_lost │
                    │                                                                          │
                    │   162 │   │   │   # just close our end.  First calling shutdown() seems  │
                    │   163 │   │   │   # cure it, but maybe using DisconnectEx() would be bet │
                    │   164 │   │   │   if hasattr(self._sock, 'shutdown') and self._sock.file │
                    │ ❱ 165 │   │   │   │   self._sock.shutdown(socket.SHUT_RDWR)              │
                    │   166 │   │   │   self._sock.close()                                     │
                    │   167 │   │   │   self._sock = None                                      │
                    │   168 │   │   │   server = self._server                                  │
                    ╰──────────────────────────────────────────────────────────────────────────╯
                    ConnectionResetError: [WinError 10054] An existing connection was forcibly
                    closed by the remote host
[11:44:58] INFO     📬 Updating content index via API call by obsidian client                          indexer.py:75           INFO     💎 Setting up search for markdown notes                                           indexer.py:255[11:45:43] ERROR    🚨 Failed to setup markdown: Compressed file ended before the end-of-stream       indexer.py:268                    marker was reached
                    ╭────────────────────── Traceback (most recent call last) ──────────────────────╮
                    │ C:\Users\james291\AppData\Roaming\Python\Python311\site-packages\khoj\routers │
                    │ \indexer.py:257 in configure_content                                          │
                    │                                                                               │
                    │   254 │   │   │                                                               │
                    │   255 │   │   │   logger.info("💎 Setting up search for markdown notes")      │
                    │   256 │   │   │   # Extract Entries, Generate Markdown Embeddings             │
                    │ ❱ 257 │   │   │   content_index.markdown = text_search.setup(                 │
                    │   258 │   │   │   │   MarkdownToJsonl,                                        │
                    │   259 │   │   │   │   files.get("markdown"),                                  │
                    │   260 │   │   │   │   content_config.markdown,                                │
                    │                                                                               │
                    │ C:\Users\james291\AppData\Roaming\Python\Python311\site-packages\khoj\search_ │
                    │ type\text_search.py:210 in setup                                              │
                    │                                                                               │
                    │   207 │   config.compressed_jsonl = resolve_absolute_path(config.compressed_j │
                    │   208 │   previous_entries = []                                               │
                    │   209 │   if config.compressed_jsonl.exists() and not regenerate:             │
                    │ ❱ 210 │   │   previous_entries = extract_entries(config.compressed_jsonl)     │
                    │   211 │   entries_with_indices = text_to_jsonl(config).process(               │
                    │   212 │   │   previous_entries=previous_entries, files=files, full_corpus=ful │
                    │   213 │   )                                                                   │
                    │                                                                               │
                    │ C:\Users\james291\AppData\Roaming\Python\Python311\site-packages\khoj\search_ │
                    │ type\text_search.py:58 in extract_entries                                     │
                    │                                                                               │
                    │    55                                                                         │
                    │    56 def extract_entries(jsonl_file) -> List[Entry]:                         │
                    │    57 │   "Load entries from compressed jsonl"                                │
                    │ ❱  58 │   return list(map(Entry.from_dict, load_jsonl(jsonl_file)))           │
                    │    59                                                                         │
                    │    60                                                                         │
                    │    61 def compute_embeddings(                                                 │
                    │                                                                               │
                    │ C:\Users\james291\AppData\Roaming\Python\Python311\site-packages\khoj\utils\j │
                    │ sonl.py:27 in load_jsonl                                                      │
                    │                                                                               │
                    │   24 │   │   jsonl_file = open(get_absolute_path(input_path), "r", encoding=" │
                    │   25 │                                                                        │
                    │   26 │   # Read JSONL file                                                    │
                    │ ❱ 27 │   for line in jsonl_file:                                              │
                    │   28 │   │   data.append(json.loads(line.strip(empty_escape_sequences)))      │
                    │   29 │                                                                        │
                    │   30 │   # Close JSONL file                                                   │
                    │                                                                               │
                    │ C:\Python311\Lib\gzip.py:314 in read1                                         │
                    │                                                                               │
                    │   311 │   │                                                                   │
                    │   312 │   │   if size < 0:                                                    │
                    │   313 │   │   │   size = io.DEFAULT_BUFFER_SIZE                               │
                    │ ❱ 314 │   │   return self._buffer.read1(size)                                 │
                    │   315 │                                                                       │
                    │   316 │   def peek(self, n):                                                  │
                    │   317 │   │   self._check_not_closed()                                        │
                    │                                                                               │
                    │ C:\Python311\Lib\_compression.py:68 in readinto                               │
                    │                                                                               │
                    │    65 │                                                                       │
                    │    66 │   def readinto(self, b):                                              │
                    │    67 │   │   with memoryview(b) as view, view.cast("B") as byte_view:        │
                    │ ❱  68 │   │   │   data = self.read(len(byte_view))                            │
                    │    69 │   │   │   byte_view[:len(data)] = data                                │
                    │    70 │   │   return len(data)                                                │
                    │    71                                                                         │
                    │                                                                               │
                    │ C:\Python311\Lib\gzip.py:518 in read                                          │
                    │                                                                               │
                    │   515 │   │   │   if uncompress != b"":                                       │
                    │   516 │   │   │   │   break                                                   │
                    │   517 │   │   │   if buf == b"":                                              │
                    │ ❱ 518 │   │   │   │   raise EOFError("Compressed file ended before the "      │
                    │   519 │   │   │   │   │   │   │      "end-of-stream marker was reached")      │
                    │   520 │   │                                                                   │
                    │   521 │   │   self._add_read_data( uncompress )                               │
                    ╰───────────────────────────────────────────────────────────────────────────────╯
                    EOFError: Compressed file ended before the end-of-stream marker was reached
           INFO     🖨️ Setting up search for pdf                                                       indexer.py:286
[11:45:49] INFO     Setting up text search model with normalize {normalize} regenerate            text_search.py:225                    {regenerate}
           INFO     📩 Indexing 193 new text entries.                                              text_search.py:83Batches:   0%|                                                                               | 0/7 [00:00<?, ?it/s][11:45:53] INFO     📬 Updating content index via Scheduler                                         configure.py:115
[11:45:54] INFO     💎 Setting up search for markdown notes                                           indexer.py:255Batches:  29%|████████████████████▎                                                  | 2/7 [01:01<02:24, 28.94s/it][11:46:53] INFO     📬 Updating content index via Scheduler                                         configure.py:115
[11:46:54] INFO     💎 Setting up search for markdown notes                                           indexer.py:255Batches: 100%|███████████████████████████████████████████████████████████████████████| 7/7 [01:38<00:00, 14.01s/it]
[11:47:27] INFO     📩 Saved computed text embeddings to                                          text_search.py:103                    C:\Users\james291\.khoj\content\pdf\pdf_embeddings.pt
[11:47:28] INFO     📪 Content index updated via API call by obsidian client                          indexer.py:158           INFO     127.0.0.1:59974 - "POST /api/v1/index/update?force=false&client=obsidian         h11_impl.py:431                    HTTP/1.1" 200
[11:47:48] INFO     Setting up text search model with normalize {normalize} regenerate            text_search.py:225                    {regenerate}
           INFO     📩 Indexing 35 new text entries.                                               text_search.py:83Batches:   0%|                                                                               | 0/2 [00:00<?, ?it/s][11:47:53] INFO     📬 Updating content index via Scheduler                                         configure.py:115
[11:47:54] INFO     💎 Setting up search for markdown notes                                           indexer.py:255Batches: 100%|███████████████████████████████████████████████████████████████████████| 2/2 [00:21<00:00, 10.74s/it]
[11:48:10] INFO     📩 Saved computed text embeddings to                                          text_search.py:103                    C:\Users\james291\.khoj\content\markdown\markdown_embeddings.pt
[11:48:53] INFO     📬 Updating content index via Scheduler                                         configure.py:115[11:49:05] INFO     🖨️ Setting up search for pdf                                                       indexer.py:286
[11:49:07] INFO     💎 Setting up search for markdown notes                                           indexer.py:255[11:49:08] INFO     Setting up text search model with normalize {normalize} regenerate            text_search.py:225                    {regenerate}
           INFO     📩 Saved computed text embeddings to                                          text_search.py:103                    C:\Users\james291\.khoj\content\pdf\pdf_embeddings.pt
           INFO     📪 Content index updated via Scheduler                                          configure.py:120[11:49:18] ERROR    🚨 Failed to setup markdown: Not a gzipped file (b'\xb8\xad')                     indexer.py:268                    ╭────────────────────── Traceback (most recent call last) ──────────────────────╮
                    │ C:\Users\james291\AppData\Roaming\Python\Python311\site-packages\khoj\routers │
                    │ \indexer.py:257 in configure_content                                          │
                    │                                                                               │
                    │   254 │   │   │                                                               │
                    │   255 │   │   │   logger.info("💎 Setting up search for markdown notes")      │
                    │   256 │   │   │   # Extract Entries, Generate Markdown Embeddings             │
                    │ ❱ 257 │   │   │   content_index.markdown = text_search.setup(                 │
                    │   258 │   │   │   │   MarkdownToJsonl,                                        │
                    │   259 │   │   │   │   files.get("markdown"),                                  │
                    │   260 │   │   │   │   content_config.markdown,                                │
                    │                                                                               │
                    │ C:\Users\james291\AppData\Roaming\Python\Python311\site-packages\khoj\search_ │
                    │ type\text_search.py:210 in setup                                              │
                    │                                                                               │
                    │   207 │   config.compressed_jsonl = resolve_absolute_path(config.compressed_j │
                    │   208 │   previous_entries = []                                               │
                    │   209 │   if config.compressed_jsonl.exists() and not regenerate:             │
                    │ ❱ 210 │   │   previous_entries = extract_entries(config.compressed_jsonl)     │
                    │   211 │   entries_with_indices = text_to_jsonl(config).process(               │
                    │   212 │   │   previous_entries=previous_entries, files=files, full_corpus=ful │
                    │   213 │   )                                                                   │
                    │                                                                               │
                    │ C:\Users\james291\AppData\Roaming\Python\Python311\site-packages\khoj\search_ │
                    │ type\text_search.py:58 in extract_entries                                     │
                    │                                                                               │
                    │    55                                                                         │
                    │    56 def extract_entries(jsonl_file) -> List[Entry]:                         │
                    │    57 │   "Load entries from compressed jsonl"                                │
                    │ ❱  58 │   return list(map(Entry.from_dict, load_jsonl(jsonl_file)))           │
                    │    59                                                                         │
                    │    60                                                                         │
                    │    61 def compute_embeddings(                                                 │
                    │                                                                               │
                    │ C:\Users\james291\AppData\Roaming\Python\Python311\site-packages\khoj\utils\j │
                    │ sonl.py:27 in load_jsonl                                                      │
                    │                                                                               │
                    │   24 │   │   jsonl_file = open(get_absolute_path(input_path), "r", encoding=" │
                    │   25 │                                                                        │
                    │   26 │   # Read JSONL file                                                    │
                    │ ❱ 27 │   for line in jsonl_file:                                              │
                    │   28 │   │   data.append(json.loads(line.strip(empty_escape_sequences)))      │
                    │   29 │                                                                        │
                    │   30 │   # Close JSONL file                                                   │
                    │                                                                               │
                    │ C:\Python311\Lib\gzip.py:314 in read1                                         │
                    │                                                                               │
                    │   311 │   │                                                                   │
                    │   312 │   │   if size < 0:                                                    │
                    │   313 │   │   │   size = io.DEFAULT_BUFFER_SIZE                               │
                    │ ❱ 314 │   │   return self._buffer.read1(size)                                 │
                    │   315 │                                                                       │
                    │   316 │   def peek(self, n):                                                  │
                    │   317 │   │   self._check_not_closed()                                        │
                    │                                                                               │
                    │ C:\Python311\Lib\_compression.py:68 in readinto                               │
                    │                                                                               │
                    │    65 │                                                                       │
                    │    66 │   def readinto(self, b):                                              │
                    │    67 │   │   with memoryview(b) as view, view.cast("B") as byte_view:        │
                    │ ❱  68 │   │   │   data = self.read(len(byte_view))                            │
                    │    69 │   │   │   byte_view[:len(data)] = data                                │
                    │    70 │   │   return len(data)                                                │
                    │    71                                                                         │
                    │                                                                               │
                    │ C:\Python311\Lib\gzip.py:499 in read                                          │
                    │                                                                               │
                    │   496 │   │   │   │   # If the _new_member flag is set, we have to            │
                    │   497 │   │   │   │   # jump to the next member, if there is one.             │
                    │   498 │   │   │   │   self._init_read()                                       │
                    │ ❱ 499 │   │   │   │   if not self._read_gzip_header():                        │
                    │   500 │   │   │   │   │   self._size = self._pos                              │
                    │   501 │   │   │   │   │   return b""                                          │
                    │   502 │   │   │   │   self._new_member = False                                │
                    │                                                                               │
                    │ C:\Python311\Lib\gzip.py:468 in _read_gzip_header                             │
                    │                                                                               │
                    │   465 │   │   self._stream_size = 0  # Decompressed size of unconcatenated st │
                    │   466 │                                                                       │
                    │   467 │   def _read_gzip_header(self):                                        │
                    │ ❱ 468 │   │   last_mtime = _read_gzip_header(self._fp)                        │
                    │   469 │   │   if last_mtime is None:                                          │
                    │   470 │   │   │   return False                                                │
                    │   471 │   │   self._last_mtime = last_mtime                                   │
                    │                                                                               │
                    │ C:\Python311\Lib\gzip.py:428 in _read_gzip_header                             │
                    │                                                                               │
                    │   425 │   │   return None                                                     │
                    │   426 │                                                                       │
                    │   427 │   if magic != b'\037\213':                                            │
                    │ ❱ 428 │   │   raise BadGzipFile('Not a gzipped file (%r)' % magic)            │
                    │   429 │                                                                       │
                    │   430 │   (method, flag, last_mtime) = struct.unpack("<BBIxx", _read_exact(fp │
                    │   431 │   if method != 8:                                                     │
                    ╰───────────────────────────────────────────────────────────────────────────────╯
                    BadGzipFile: Not a gzipped file (b'\xb8\xad')`
                 
So to me it looks like there was a connection issue (i unplugged my laptop and the wifi dropped out at 11:44) and the .gz file (which may have been open at the time while Khoj was setting up the index??) was somehow not saved down properly.  Which let to the gzip error on the next Scheduler update? 

No idea if this helps with anything..

**Comment by debanjum** [comment]
Hi @jh0274, thanks for the investigation and sharing your logs. This corruption during index save is a separate but valid issue from the original.  It should be fixed once we merge the recent [rearchitecture changes](https://github.com/khoj-ai/khoj/compare/master...features/multi-user-support-khoj), as Khoj will be start using a DB to keep the index. So we'll get ACID guarantees
