### ISSUE TITLE
Support for Offline Chat Models

### ISSUE THREAD

**Issue by FrankCold** [khoj-ai/khoj#201]
Hello! Could you provide support for a way to replace openai llm with locally hosted custom model calls? This would be great! (we just need a way to provide string with a response to your plugin)

Cheers!

**Comment by debanjum** [comment]
Hey @FrankCold, do you have specific custom models you want to try use? I plan to test out quality of Khoj Chat using Alpaca/Llama. And if it's not too bad, to provide it as a configurable option for folks who want completely local chat. Would that suffice for your use-case?

Let me also think if there's a generic way to swap out chat models that isn't too brittle for the fast changing LLM space. (i.e an interface to provide input query and get response message)

**Comment by FrankCold** [comment]
I was referring exactly to Alpaca/Llama! But I would also like to test other combinations. Providing a configurable option would definitely allow me to do what I plan to do!

I, too, think that llms are developing so fast that Khoj could be compatible with them all the time if it allowed models to be plugged in more universally.

The way LangChain does it (albeit in a different area) comes to mind here: [custom LLM wrapper](https://python.langchain.com/en/latest/modules/models/llms/examples/custom_llm.html)
Providing the ability to plug in personalised LLM calls. Something similar would be ideal.

**Comment by whatSocks** [comment]
Perhaps as an intermediate step it could use a model hosted on huggingface?

 I'm using the https://text-gen.com/ plugin and it would be nice to have something similar

**Comment by replete** [comment]
I've been looking around this obsidian local llm problem space, and stumbling on this issue I wanted to mention [obsidian-local-llm](https://github.com/zatevakhin/obsidian-local-llm) which exposes an OpenAI-like API with custom models which might work with Khoj for this use case

**Comment by debanjum** [comment]
Hi @replete,

Thanks for the references! Did you try Khoj chat? And what did you find lacking in it?

I was looking into integrating offline chat models into Khoj earlier. The 2 main issues I currently see are:
1. The current set of prompts used by Khoj are meant for the OpenAI GPT LLMs. I do not expect them to translate well to Llama based models like Vicuna, Alpaca as they require a different formatting. This will require creating custom prompt to LLM model mapping and will require Khoj to be aware of which LLM model is being used for chat
2. Setting up offline chat model is not easy for non-developers right now. E.g (all?) Llama models require downloading base model weights separately, including the [obsidian-local-llm](https://github.com/zatevakhin/obsidian-local-llm) plugin you shared.

Both these issues can be fixed. But it'll require some time and effort

**Comment by replete** [comment]
@debanjum Apologies for delay in response.

I've been following the space and emerging tech around local LLMs because I'm  interested in NLI for the local obsidian second brain. Khoj looks easily like the best solution so far by a distance, everything else seems to be simple prompt-in-obsidian.

What I'm hoping for in the future beyond search is to be able to map entity keywords etc to data in my vault to allow querying with my terms and initiate actions. An obsidian chat interface that does obsidian things, and ideally plugging in a more general local LLM (e.g. quantized wizard uncensored 13b) an assistant interface that can somehow use obsidian as a context. I know that's complicated, I've been trying to understand this myself, looking at things like Gorilla and Langchain.

Obsidian feels like offline web services with your own data, I really really like this and hope to eventually make the offline second brain something I can talk to like I would chatGPT. That is obviously not easy, but I'm seeing the components emerge and wonder how far away a truly offline personal data system + assistant is.

**Comment by debanjum** [comment]
Thanks for putting down your thoughts in details ❤️. It gives more context on what folks are looking for with a tool like Khoj. See my responses to it below:

> Khoj looks easily like the best solution so far by a distance

Thanks for your kind words! 

> be able to map entity keywords etc to data in my vault to allow querying with my terms and initiate action

Can you given an example of what this may look like? Do you want to trigger actions using specific keywords?

> An obsidian chat interface that does obsidian things

By Obsidian things, do you mean like execute actions within Obsidian? Example: Create a note in Obsidian. Or something else?

> an assistant interface that can somehow use obsidian as a context.

What kind of Obsidian context do you imagine this assistant using?

> I know that's complicated, I've been trying to understand this myself, looking at things like Gorilla and Langchain.

Hacking up offline chat for a single user, machine should be very doable. Actions would be more work, but doable as well IMO. Doing both in a way that generalizes to a variety of users, machines, use-cases is where it **currently** gets ~annoying~ interesting 😅

We're trying to find ways to get AI personal assistants in the hands of the most people in/with the least time/effort. Making Khoj easy for more folks to use sounds like the first step in that direction. 
See the [announcement](https://github.com/khoj-ai/khoj/discussions/229) for more details

**Comment by sabaimran** [comment]
I came across a pretty interesting project today via Reddit called [gpt4all](https://github.com/nomic-ai/gpt4all). It looks like they've collated a bunch of powerful open source LLMs into a single repository that's relatively easy to plug and play. I'll spend some time experimenting with this to see if this can help us get setup with offline chat models. [Link to documentation](https://docs.gpt4all.io/gpt4all_python.html).
