### ISSUE TITLE
[Obsidian Plugin] Sidebar model

### ISSUE THREAD

**Issue by wwjCMP** [khoj-ai/khoj#203]
Hope to provide a sidebar mode for the search and conversation functions within Obsidian plugins. I believe that this mode will sometimes result in higher work efficiency than the current floating window.

**Comment by debanjum** [comment]
Hey @wwjCMP, thanks for the feedback! Agreed that having Khoj as a sidebar in Obsidian can be a more useful view. Let me look into how much effort that'd take.

**Comment by debanjum** [comment]
You can chat with Khoj from the right sidebar in Obsidian since a few months now!
