### ISSUE TITLE
Remove PyQT GUI

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#251]
This is sort of a "legacy" approach for updating configuration settings for Khoj. We should probably nix the GUI and move towards funneling all configuration to be driven through the web-based UI settings pages we've been focused on as the central location.

**Comment by debanjum** [comment]
The PyQt configuration GUI can be totally be replaced with the much better
looking web config UI. But PyQt is currently also used to create the Khoj
desktop apps so it can't be removed completely.

**Comment by sabaimran** [comment]
This is like the ~first step in the direction of removing the GUI #263

**Comment by sabaimran** [comment]
Completed with https://github.com/khoj-ai/khoj/pull/304
