### ISSUE TITLE
Support Image Search in Khoj Obsidian

### ISSUE THREAD

**Issue by debanjum** [khoj-ai/khoj#258]
Support searching for images in Obsidian Vault using natural language with Khoj. 
Khoj already supports searching for images. 
But the Obsidian plugin needs to be updated to 
1. Index images in vault
2. Show images in the search modal (Rendering images is not currently fast enough for search as you type, so either make it fast enough or do image search separately)

**Comment by sabaimran** [comment]
Closing for now as we aren't currently supporting/maintaining image search.
