### ISSUE TITLE
Document using Virtualenv if Conflicting Dependencies

### ISSUE THREAD

**Issue by chookity-pokk** [khoj-ai/khoj#276]
Trying to install I get the below error. Which means that for me to install khoj I had to use the command `python -m pip install khoj-assistant --break-system-packages` or create a virtual environment for it, which I don't think would work in this case?

Would be nice if there was a package for it to be able to get around this because using `--break-system-packages` doesn't exactly feel safe haha.

```
⋊> ~ python -m pip install khoj-assistant                                                                                                                                                                 
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.

    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.

    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-syst
em-packages.
hint: See PEP 668 for the detailed specification.
```

I am using Arch Linux which was updated earlier today with Python 3.11.3 and pip version 23.1.2

**Comment by chookity-pokk** [comment]
If I were to use a virtual environment would I still be able to use it within Emacs?

**Comment by debanjum** [comment]
Yeah, khoj follows a client server architecture. So the emacs package just needs to know the url where the khoj server is running (default at `http://localhost:8000`)

The khoj emacs package does try to install, start the khoj server (by calling `khoj`) if it doesn't find the server running at `khoj-server-url`. To allow that you can either using pipx or disable auto-setup with `setq khoj-auto-setup nil`

**Comment by sabaimran** [comment]
Thanks for raising the issue, @chookity-pokk ! I hope no one is installing with `--break-system-packages`. When in doubt, always use virtual environments. We should update this in the docs.
