### ISSUE TITLE
Make usage of configuration fields more clear in the settings page

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#281]
- `input-files` and `input-filter` should be more clear
- `input-filter` should probably just be directories, and we should take care of the logic of appending `**/*.{file_type}`
- `input-files` should be maybe be called file paths

**Comment by debanjum** [comment]
Improved field names and provided more guidance (via tooltip, placeholder) to setup Khoj via web settings UI
 
| Before | After |
|--------|--------|
| <img width="300" alt="LessDescriptiveSettings" src="https://github.com/khoj-ai/khoj/assets/6413477/b2898f29-9fee-4f76-a440-bdf819bbfcaa"> | <img width="300" alt="MoreDescriptiveSettings" src="https://github.com/khoj-ai/khoj/assets/6413477/79d38176-9a07-4fee-adff-e0819f8a198a"> |
