### ISSUE TITLE
Required PDF files when indexing on start

### ISSUE THREAD

**Issue by noghartt** [khoj-ai/khoj#291]
The script to index files with Khoj, is trying to find some PDF files on the specific folder.

What is the problem? I don't have any PDF, so it's breaking the `configure.py` on this [line](https://github.com/khoj-ai/khoj/blob/master/src/khoj/configure.py#L131).

If I add some random PDF inside the folder, the `khoj` starts.

**Comment by sabaimran** [comment]
Hi @noghartt! Sorry for the setup issues. Could you tell me which OS you're using + which interface? Are you using Obsidian, Emacs, or just Web?

**Comment by noghartt** [comment]
> Hi @noghartt! Sorry for the setup issues. Could you tell me which OS you're using + which interface? Are you using Obsidian, Emacs, or just Web?

OS: macOS Ventura 13.4.0

I'm using Obsidian interface. But I think that it's happening with all interfaces.

**Comment by sabaimran** [comment]
Ah, got it. I think this is specific to the way Obsidian modifies the configuration on startup. If you go to the Web UI and disable the existing PDF configuration, it should work correctly. Let me test & patch the issue on the Obsidian interface.

**Comment by noghartt** [comment]
> @noghartt I'm going to include this in the next release today, but you can use this command if you want it sooner:
> 
> ```shell
> # Maps to the latest commit on the master branch
> pip install --upgrade --pre khoj-assistant
> ```

Cool! Thank you so much!
