### ISSUE TITLE
Test out the windows applications

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#294]
After the latest release, test out the application installation process on Windows.

Now that we have a working release pipeline generally for desktop applications, we might also be able to direct people to directly use those releases 👀.

**Comment by sabaimran** [comment]
Working on arm64 machines after this commit: https://github.com/khoj-ai/khoj/commit/31e933207f52fcb0c4100a7c48561a5a14c73ec8

Included full instructions for using windows in this discussion: https://github.com/khoj-ai/khoj/discussions/305

**Comment by debanjum** [comment]
Moved the Khoj setup instructions on windows to the (new) [Khoj wiki](https://github.com/khoj-ai/khoj/wiki/Install-Khoj-on-Windows-%F0%9F%AA%9F)
