### ISSUE TITLE
Docker run environment can't deep link to original file

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#30]
The way we are mounting volumes in the Docker container means that it doesn't have access to the original file location in the user's filesystem. Due to this, deep linking (in org notes) will fail, as it will try to generate the link based on the mounted volume's name.

To reproduce the behavior in the Docker environment:
1. Run a query against your org notes
2. Investigate the `PROPERTIES` bag
3. Look at the link associated with the `LINE` and `SOURCE` fields; they should be referencing a filepath based on the mounted volume, rather than the local directory

There are some different ways we could work around this, ranging from more to less messy. We could expose a mapping somewhere outside of the `docker-compose.yml` file that specifies the local directory for the given mounted volume. We could have the mounted volumes follow the same naming convention as the local directory, and provide a standardized mapping in the `config.yml`.

**Comment by debanjum** [comment]
Note (to self?): Will mounting volumes at same path in docker container as it was in the users filesystem solve this issue?
This can be simplified if we generate the docker and khoj config files via a script for this use-case

**Comment by sabaimran** [comment]
Closing this as unactionable for now. We won't support this use case.
