### ISSUE TITLE
Analyze Khoj Memory Consumption

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#303]
Khoj hits high RAM usage on large enough knowledge bases. Can the memory utilization by Khoj be improved?
Related issues: #195, #301

**Comment by sriramr98** [comment]
Hey @sabaimran . I would love to pick this up and brainstorm with you to build a solution for this.

**Comment by sabaimran** [comment]
Hey @sriramr98 ! Sorry for the delayed response here. I think this one might be a big lift -- there are some obvious approaches we can prioritize to mitigate this issue, but they're non-trivial to implement. We'll have to integrate vector storage here. I'll try to go through our backlog and flag the issues with `good-first-issue`.
