### ISSUE TITLE
Build images for ARM-based machines

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#312]
This is blocked behind https://github.com/actions/runner-images/issues/5631, which has an indeterminant timeline. We can setup a manual workflow in the meantime to build + bush arm-based images for MacOS at the very least.

**Comment by KeithIMyers** [comment]
I have a m1 mac that I barely use if you want to setup a actions agent on.

**Comment by debanjum** [comment]
@KeithIMyers, thanks for the kind offer! 🙏🏾 

Let us try build the images on the m1 macs we use for a bit. But if that doesn't work out, I'll reach out to you

**Comment by jmilldotdev** [comment]
this would be great 🙏

**Comment by amitkot** [comment]
I would appreciate an update on this, if possible 🙏

**Comment by debanjum** [comment]
Hi @amitkot, Khoj is already available as a desktop app for Mac arm64. Check the Khoj GitHub releases for the latest arm64 build for Macs. This issue is to automate creating Mac arm64 builds for khoj on triggering a release.

**Comment by srid** [comment]
> Hi @amitkot, Khoj is already available as a desktop app for Mac arm64. Check the Khoj GitHub releases for the latest arm64 build for Macs. This issue is to automate creating Mac arm64 builds for khoj on triggering a release.

Where? I only see amd64 builds for mac:

<img width="246" alt="image" src="https://github.com/khoj-ai/khoj/assets/3998/3d198906-8328-4dfc-9151-41bf1c229cf0">

https://github.com/khoj-ai/khoj/releases

**Comment by sabaimran** [comment]
Hey @srid! Yes, GitHub had some issues updating our latest release and we weren't able to update it. 

We're actually going to be deprecating this setup process in the next release and fallback again to a `pip`-first setup. The desktop builds were tricky to maintain and added development constraints.

**Comment by debanjum** [comment]
Closing this issue as we do have Mac ARM desktop builds. I've recently also added an automated workflow to trigger desktop builds that include ARM64 builds for Macs in 68ac1e01
