### ISSUE TITLE
Add setup instructions to Notion, Github plugins in the web UI

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#314]
It's not immediately clear how to setup the Github, Notion integrations right away from the settings UI. Add links to instructions in the web UI as well as READMEs.

**Comment by debanjum** [comment]
Added setup instruction to [Notion](https://github.com/khoj-ai/khoj/wiki/Setup-Notion-Integration), [Github](https://github.com/khoj-ai/khoj/wiki/Setup-Github-integration) plugin to the (newly created) Khoj wiki on Github
