### ISSUE TITLE
Add a demo for semantic search using Harry Potter data

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#33]
Idea, riffing and open to modification!

We could host a standalone demo for Semantic Search using Harry Potter as the input data to generate embeddings. 
We could use a platform like Streamlit to quickly deploy a simple, nice UI that simply calls into a service hosting a model trained on that data in the backend. 

Users could make detailed queries like, "Where did Harry first catch a snitch?" Or "What was Aunt Petunia's favorite desert?" Or equivalent.

**Comment by sabaimran** [comment]
[Screencast from 05-29-2023 02:08:01 PM.webm](https://github.com/debanjum/khoj/assets/65192171/d6362e7c-05d9-4502-b70b-cfe0d6b5aa2a)

**Comment by sabaimran** [comment]
[Screencast from 05-29-2023 02:23:29 PM.webm](https://github.com/debanjum/khoj/assets/65192171/7daa38d3-cfbb-4604-954f-e489f36e48c1)

**Comment by debanjum** [comment]
I think we can close this as we've created video demos like above indexing Paul Graham essays and live demos for Khoj at https://faq.khoj.dev indexing the Khoj github repository to find relevant commits, issues etc
