### ISSUE TITLE
Error installing khoj server in WSL: requirement pyside6>=6.5.1

### ISSUE THREAD

**Issue by Hopsakee** [khoj-ai/khoj#335]
I get the following error trying to install in WSL.

ERROR: Could not find a version that satisfies the requirement pyside6>=6.5.1 (from khoj-assistant) (from versions: 6.0.0a1.dev1606911628, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.2.0, 6.2.1, 6.2.2, 6.2.2.1, 6.2.3, 6.2.4)
ERROR: No matching distribution found for pyside6>=6.5.1 (from khoj-assistant)

I created a Conda environment in which I ran the following command:
```
python3 -m pip install khoj-assistant
```

I installed the latest PySide6 (6.5.1) using pip. But I still have the same error.

Any solutions?

**Comment by sabaimran** [comment]
Hey, sorry about the installation issues!

Could you share your machine specs? I'm curious whether you're on an ARM64-based image.

I've seen the same error on an ubuntu docker image within my MacOS, and eventually narrowed it down to the [lack of a PySide build](https://pypi.org/project/PySide6/#files) for `arm64`-based Linux machines.

**Comment by Hopsakee** [comment]
I have a:
Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz

So unfortunately it's not ARM.

But it is a machine managed by my employer. So there might be something funky going on there.

Also I've got it working by installing it under powershell. And the WSL installations does work on my private PC. 

So in my opinion this problem can be placed low on the priority list. The only real problem is, is the annoying feeling I don't understand what's happening.

**Comment by debanjum** [comment]
Not sure why the pip install attempt under conda doesn't show the newer pyside's (>6.2.4) as an installable option. Some cached packages?

Anyway glad you got it to work with powershell on the work machine and with WSL on your personal machine! 
I'll close this issue as nothing actionable to do from our end. But feel free to comment here if you do figure it out.
