### ISSUE TITLE
Can't access on localhost:42110 anymore. Running in background.

### ISSUE THREAD

**Issue by sm18lr88** [khoj-ai/khoj#336]
My computer: Windows 11 Pro, latest setup, Intel 7th gen, GPU 1050 mobile, etc.

I used it successfully during the initial setup, ingestion of docs, and using the chat and search functions without issues. 
I then closed it, and opened it again. Seemed to be running fine in the background terminal, but I couldn't access it on the browser at localhost:42110, 3000 or 8000 (idk where I got those other port number ideas). In fact it's currently at 50% progress for indexing some files.

The address just tells me: "This site can’t be reached. localhost refused to connect. ERR_CONNECTION_REFUSED"

So I upgraded the install, which downloaded new versions of a few packages, and I still can't access it. 

How do I find out the address for access?

**Comment by sm18lr88** [comment]
Ah, well, after finishing what it was doing, it automatically opened in the browser.

**Comment by debanjum** [comment]
Yeah, the latest update fixed some index corruption issues but required regenerating the index on first run. The app search and chat functionality doesn't become available until indexing is complete, which is why you couldn't access that
