### ISSUE TITLE
pdf and image search capabilities?

### ISSUE THREAD

**Issue by fkgruber** [khoj-ai/khoj#337]
What are the capabilities of the pdf and image search? 
recognize objects? handwriting? print text?, recognize math?

**Comment by sabaimran** [comment]
Hey @fkgruber! PDF indexing will take in any of the text in the PDF, but it won't do additional processing on any images within the document. Images works well for object, place, action queries. For example "Hiking Mt. Rainier", "Falcons flying by a tree", "classroom at night" should all be good questions, but "x+y=5" or searching for handwriting (like OCR) won't work as well.

Do you have related feature requests or use cases in mind?

I think we answered this [in Discord as well](https://discord.com/channels/1112065956647284756/1112065956647284759/1131974619386089487), but duplicating in case anyone else has this question in Github.
