### ISSUE TITLE
Does opeanai keep the notes you send them?

### ISSUE THREAD

**Issue by fkgruber** [khoj-ai/khoj#340]
When using the chat feature  I see in the documentation that :
"These notes, the last few messages and associated metadata is passed to ChatGPT along with your query for a response"
Do you know if openai just keeps this information and use it for future training?

I can see that being a problem is say your ideas end up being given as future chat response, etc.
thanks
FKG

**Comment by sabaimran** [comment]
Hey @fkgruber , according to OpenAI's [data usage policy](https://openai.com/policies/api-data-usage-policies), they say:
> 1. OpenAI will not use data submitted by customers via our API to train or improve our models, unless you explicitly decide to share your data with us for this purpose. You can [opt-in to share data](https://docs.google.com/forms/d/e/1FAIpQLSevgtKyiSWIOj6CV6XWBHl1daPZSOcIWzcUYUXQ1xttjBgDpA/viewform).
> 2. Any data sent through the API will be retained for abuse and misuse monitoring purposes for a maximum of 30 days, after which it will be deleted (unless otherwise required by law).

I'd recommend not to index anything for chat which contains particularly sensitive information, but this is at least the company policy.
