### ISSUE TITLE
Missing instructions for the precompiled deb artifacts

### ISSUE THREAD

**Issue by ngirard** [khoj-ai/khoj#348]
I couldn't find any instructions on how to install / configure / use the precompiled debian packages.

Cheers ! !

**Comment by sabaimran** [comment]
Very fair point. Once we have desktop images for our target architectures for the next release (target end of week), we should also add instructions in [the installation docs](https://docs.khoj.dev/#/setup) to explain how to use them.

**Comment by sabaimran** [comment]
Added instructions [here](https://docs.khoj.dev/#/desktop_installation?id=linux)

**Comment by ngirard** [comment]
Great, thanks ! I'll give it a try as soon as I can
