### ISSUE TITLE
[Linux] Non-adherence to XDG Base Directory Specification

### ISSUE THREAD

**Issue by ngirard** [khoj-ai/khoj#350]
The official documentation mentions that the configuration file is to be found under `~/.khoj`.

I'd expect them to be found in `$XDG_CONFIG_HOME/.khoj`, as per the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by debanjum** [comment]
@link2xt the offline chat model goes under `~/.cache/gpt4all/` and the search models goes into `~/.khoj/search`.
You should just delete those directories for now if you don't want your khoj config wiped for now.

But yeah, we should put at least the `.khoj` folder under $XDG_CONFIG_HOME when it's set

**Comment by debanjum** [comment]
Khoj doesn't rely on `~/.khoj` directory anymore. It is now configured via an Django admin panel (with config stored in a postgresDB). So this issue has become stale
