### ISSUE TITLE
Unsure how to configure asymmetric encoder with a non-existent config file

### ISSUE THREAD

**Issue by ngirard** [khoj-ai/khoj#351]
The [documentation](https://docs.khoj.dev/#/advanced) instructs to

> Manually update `search-type > asymmetric > encoder` to `paraphrase-multilingual-MiniLM-L12-v2` in your `~/.khoj/khoj.yml` file for now. See diff of `khoj.yml` below for illustration (...)

but said file is non-existent after installing Khoj.

I'd expect a default configuration to be either described in the docs, or generated at first launch. Even better, expose a dedicated subcommand to produce the default configuration. See e.g. [Zellij](https://github.com/zellij-org/zellij) for inspiration:
```
zellij setup --help
zellij-setup 
Setup zellij and check its configuration

USAGE:
    zellij setup [OPTIONS]

OPTIONS:
        --check
            Checks the configuration of zellij and displays currently used directories

        --clean
            Disables loading of configuration file at default location, loads the defaults that
            zellij ships with

        --dump-config
            Dump the default configuration file to stdout

        (...)
```

**Comment by sabaimran** [comment]
Ah valid feedback. The `khoj.yml` does not yet exist on first run, which prevents the individual from setting a default configuration 🤔.

Once you configure any of the content types in the `settings` tab (from the web UI), the `khoj.yml` will be generated for you at `~/.khoj/khoj.yml` with the default settings. From there, you can of course edit it as you please.

I think the logic here is that we don't want to prematurely start downloading models for you if you haven't yet configured any content types. The appropriate remedy here is to allow you to configure your `search-type` settings from the web UI.
