### ISSUE TITLE
Configure khoj to Index URIs.

### ISSUE THREAD

**Issue by jax79sg** [khoj-ai/khoj#377]
I have documents on various URIs in the form of internal web URLs, smb uris. Can khoj be configure to recursively index them?

**Comment by Ellen7ions** [comment]
What does the document on the url mean? Can you describe it exactly? Do you mean a web page or a HTML file ?

**Comment by sabaimran** [comment]
Hey @jax79sg , do you mind adding a bit more detail for this request? What kind of data is in the URI? Is it just HTML pages? Is the use case that you'd like to chat with a website, or does it have your personal documents?

**Comment by debanjum** [comment]
Crawling (internal or external) websites from within Khoj isn't currently planned. You'll need to use a separate program to crawl documents on your internal network. You can then sync the crawled documents to your Khoj's knowledge base to chat with it. 

Khoj will be able to read (i.e scrape not crawl) webpages on your intranet once #936 is merged
