### ISSUE TITLE
Failure to download model llama-2 (Invalid model file)

### ISSUE THREAD

**Issue by JakeStevenson** [khoj-ai/khoj#379]
Running on macOS Ventura, M2 processor with 32G RAM.

From a fresh configuration of Khoj, I attempt to enable local chat, but after downloading the model, it errors, saying it is unable to instantiate it.

```
[07:59:56] INFO     🌘 Starting Khoj                                                                                            main.py:66
           INFO     💬 Setting up conversation processor                                                                  configure.py:286
llama-2-7b-chat.ggmlv3.q4_K_S.bin: 100%|█████████████████████████████████████████████████████████████| 3.06G/3.06G [02:15<00:00, 24.2MB/s]
Found model file at  /Users/jakes/.cache/gpt4all/llama-2-7b-chat.ggmlv3.q4_K_S.bin
Invalid model file
[08:02:12] ERROR    Failed to download model llama-2-7b-chat.ggmlv3.q4_K_S.bin from                                            utils.py:40
                    https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q3_K_M.bin to
                    /Users/jakes/.cache/gpt4all/llama-2-7b-chat.ggmlv3.q4_K_S.bin. Error: Unable to instantiate model
```

I've tried a couple of times, but so far cannot get local chat to work at all.

**Comment by briancunningham6** [comment]
I get the same on an M1 macbook. It does download the model file but the application fails to start stating Jakes error. I tried manually deleting the model file and kicking off Khoj by activating the local chat in the web interface but same error occurs

**Comment by sabaimran** [comment]
Interesting. I wonder whether something corrupted the download in between and now there might be a persistent bad file. Could be it timed out, there was a network error, or something else.

Could one of you try the following:
1. Delete the file: `rm ~/.cache/gpt4all/llama-2-7b-chat.ggmlv3.q4_K_S.bin`
2. Download the file manually: open https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q3_K_M.bin
3. Save the file to the right directory: `mv ~/Downloads/llama-2-7b-chat.ggmlv3.q3_K_M.bin ~/.cache/gpt4all/`

@briancunningham6 , does your stack trace also say that it failed to download the model?

**Comment by sabaimran** [comment]
This also relates to download storage improvements we can make, mentioned in https://github.com/khoj-ai/khoj/issues/369

**Comment by JakeStevenson** [comment]
It definitely does not indicate a timeout or partial download, I can see the progress if I watch in the console.

I manually removed the file and downloaded it using wget as you described.  This worked, so it does look like an error in the current automated download.

**Comment by briancunningham6** [comment]
Thanks [sabaimran](https://github.com/sabaimran) for following up

<img width="508" alt="image" src="https://github.com/khoj-ai/khoj/assets/210569/d53f1fa9-bfd6-43e2-bf42-6ac51c890da4">

I used wget to pull down the model and it downloads fine. Interestingly the model file is larger than the original one... 3.2gb vs 3.8gb. However I am still not able to get it running, when I enable the chat option I get the above error in the terminal.

**Comment by sabaimran** [comment]
🤔 The file I linked above should be 3.5gb (https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q4_K_S.bin). I corrected the link after posting it originally (was pointing to the medium model, rather than the small).

Can you verify the download is stored in `~/.cache/gpt4all/llama-2-7b-chat.ggmlv3.q4_K_S.bin`? It needs to match that path exactly.

**Comment by authorfunction** [comment]
I have the same exact issue (on Macbook M1 Pro, Ventura, 32GB). I downloaded from the link and copied to .cache – still getting the error (unable to instantiate).

**Comment by sabaimran** [comment]
Hm, I have the same checksum value, so doesn't seem like there's anything wrong with your download.

@authorfunction What's your setup environment? Are you using the python package, desktop application, Docker?

Sorry to be pedantic, but the file path should start with `~`. Just want to make sure that's exactly correct.

**Comment by authorfunction** [comment]
I am running in a conda environment (python=3.9.17)

I think it might be something with the python version. I actually got the chat (and model download) working earlier, but then had to reinstall because pdf search wasn't working. I just realised the earlier env probably have had some version of python 3.10. Will try to upgrade.

**Comment by sabaimran** [comment]
Sounds good! Let me know if that works. If you are not already using it,
pyenv makes it super easy to manage Python versions.

https://github.com/pyenv/pyenv

What's the error you're seeing now? In theory, the app should work with
python3.9, though I haven't tried it myself.

**Comment by sabaimran** [comment]
Hmm, given you've already verified the model can be found at the correct file path, I'm not sure what else might be going wrong here.

Could you try installing the new release? It will trigger a new download of the model. If something goes wrong this time, we might be able to debug it a bit better.

```
pip install --upgrade khoj-assistant
```

**Comment by authorfunction** [comment]
OK. So i created a completely new environment and removed all config files (.khoj/). I got the chat model downloaded and working (initalised succesfully). However after setting up the document search path and having reindexed all of my pdfs (and khoj reinstalling the search models etc) – it broke in the same way again (Found model; can't initialise). So currently it is impossible to get chat working with pdf search simultaneuosly for me.

**Comment by debanjum** [comment]
Can you share screenshots of what exactly are the errors you are seeing on the khoj backend running in your terminal?

Are you able to search your documents with Khoj at all? That is, after you index your PDF files are both search and chat not working?

**Comment by debanjum** [comment]
Thanks for sharing all these details! Yes, the stacktrace looks exactly the same. This portion of the stacktrace is the issue.

```bash
[11:05:02] INFO     💬 Setting up conversation processor                                                                   configure.py:286
Found model file at  /Users/mattslindstrom/.cache/gpt4all/llama-2-7b-chat.ggmlv3.q4_K_S.bin
Invalid model file
```

* Can you check the gpt4all version you have installed in your conda environment?
* Can you share the MD5 checksum of the downloaded model (again)

It's strange that the model fails to load if both the downloaded model's checksum and the gpt4all version are correct. 

Let me think what else could be causing this behavior (and how to reproduce this on my end)

**Comment by sabaimran** [comment]
I'm moving this discussion to https://github.com/khoj-ai/khoj/issues/406 so we can appropriately disambiguate issues :-) Thanks for your patience @authorfunction!
