### ISSUE TITLE
[feature request] FileName of Markdown files as part of content

### ISSUE THREAD

**Issue by Tom910** [khoj-ai/khoj#383]
Hi, I found your project and I started to use. And it works fine and from the box (I'm using: Windows + desktop app + llama2 + Obsidian).

Obsidian motivate to use a file name of files as main title (as `# File name`), so file name is very important information in Obsidian. But looks like khoj don't add a file name as part of content https://github.com/khoj-ai/khoj/blob/master/src/khoj/processor/markdown/markdown_to_jsonl.py#L116 . It will be cool if khoj would start to use a file name as part of content

**Comment by debanjum** [comment]
Hi @Tom910, great to hear you were able to setup Khoj with the Desktop App, Llama 2 and Obsidian on Windows!

Khoj should index index all entries with the filename they belong to. See [this portion of the code](https://github.com/khoj-ai/khoj/blob/master/src/khoj/processor/markdown/markdown_to_jsonl.py#L150) for reference. 

Are you not able to find results using the filename? 
Note: To only include results from a specific filename, you can also add `+"<name_of_file>"` to your search query. See Khoj's [query filter syntax](https://github.com/khoj-ai/khoj/blob/master/docs/search.md) for reference

**Comment by debanjum** [comment]
Marking this issue as resolved. Please feel free to re-open it if you can't get khoj to find results by filename
