### ISSUE TITLE
Prompt context window exceeded: The prompt is <n > 2048> tokens and the context window is 2048

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#386]
We should use the LlamaTokenizer in our truncation logic for better accuracy. I was using a proxy tokenizer to estimate context length, but this is a bad UX.

**Comment by wenlzhang** [comment]
Not sure if related, the following article explains a way of extending the token length of LLama 2:
https://together.ai/blog/llama-2-7b-32k
