### ISSUE TITLE
Privacy/Security: Telemetry on search and chat queries enabled by default, incorrect docs to disable.

### ISSUE THREAD

**Issue by sammcj** [khoj-ai/khoj#389]
I'll start by saying congrats on making a great, open source product that's user friendly and effective.

There is one thing that concerns me - it seems that Khoj collects telemetry which may include search and chat queries.

This is rather alarming, especially for an offline-first application.

I believe this is made worse given:

- Users are not clearly warned about this and prompted if you wish to continue.
- The [docs for disabling Telemetry](https://github.com/khoj-ai/khoj/blob/master/docs/telemetry.md#disable-telemetry)https://github.com/khoj-ai/khoj/blob/master/docs/telemetry.md#disable-telemetry are incorrect.
	- There is no `~/.khoj/khoj.yml` in the container, it seems to be baked into the image itself and located in `/app/config/khoj_docker.yml`
	- There is no way to set this configuration at runtime, or launch time without maintaining your own version of this file and mounting it in.
		- When copying that file and mounting it in with configuration changes it appears that the app makes changes to it when run, this might be ok - but the behaviour should be documented if it's going to rewrite what many users would expect to be a static config file.

I would suggest:

1. Make it clear at runtime what Telemetry is collected on the user and data.
2. Require the user to accept or disable the Telemetry in the application UI at first launch or upon change.
3. Allow setting configuration by environment variable rather than baking the config file into the container image.

**Comment by sabaimran** [comment]
Hey @sammcj ! Thanks for the positive encouragement 🙏🏾.

To clarify, you don't need to use the `khoj_docker.yml` file at all. If you do not pass it the configuration file (via `-c=khoj_docker.yml`) [on this line](https://github.com/khoj-ai/khoj/blob/master/docker-compose.yml#L28), it will indeed create it at `~/.khoj/` inside the container. The `docker-compose.yml` file is mostly provided as a scaffolding to explain how to use a docker setup with Khoj, but I do not recommend using it as-is.

If you're using the `docker-compose` flow and want to use the `khoj_docker.yml`, you can simply modify the the file manually once the container is up. But, I would recommend customizing the `docker-compose.yml` according to your needs. You'll have to restart Khoj after.

Logs are batched and sent once an hour, so you can easily start the application, disable the telemetry, and restart it.

Khoj *does not collect any search or chat queries*. As mentioned in the docs, you can see our [telemetry server](https://github.com/khoj-ai/khoj/tree/master/src/telemetry). If you see anything amiss, point it out to me and I'll hotfix it right away. You can see all the telemetry metadata [right here](https://github.com/khoj-ai/khoj/blob/master/src/khoj/routers/helpers.py#L29).

**Comment by sammcj** [comment]
Thanks for clarifying @sabaimran , I really appreciate that!
