### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pyside6>=6.5.1 

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#391]
I've been seeing this error really frequently during install, especially it seems for Docker images and WSL.

One thing to note is that `pyside` seems to [lack images for linux arm64 distros](https://pypi.org/project/PySide6/#files). That might be affecting some subset of users. This might also happen to have something to do with Python versions.

If you hit this error, please drop me the following info:
1. Your OS
2. Your version of Python (if not using Docker)
3. How you're installing Khoj (e.g., Docker, desktop application, python package, from source)

What we probably should do:
- Have two separate builds -- one for GUI images, and one for non-GUI images. This will help circumvent the GUI dependencies (like `pyside`), especially for the users who aren't intending to use the packaged application.

**Comment by sabaimran** [comment]
The same issue was [reported here](https://discord.com/channels/1112065956647284756/1112066447947083826/1135700203261927579) for a user with x86 ubuntu, across python versions 3.9-3.11.

**Comment by bborowin** [comment]
I'm seeing this on an M1 macbook (Monterey 12.6.6 / 21G646), with Docker versions as follows:

Version 4.16.2 (95914)
Engine: 20.10.22
Compose: v2.15.1
Credential Helper: v0.7.0
Kubernetes: v1.25.4
Snyk: v1.1064.0


When I try the `buildx` workaround (ie, `docker buildx build -t khoj .`) it gets me past that error but conks out at gpt4all:

```
#0 12.37 ERROR: Could not find a version that satisfies the requirement gpt4all>=1.0.7 (from khoj-assistant) (from versions: 0.1.5, 0.1.6, 0.1.7)
#0 12.37 ERROR: No matching distribution found for gpt4all>=1.0.7
```

**Comment by kforner** [comment]
```
pip3 install khoj-assistant
[...]
ERROR: Could not find a version that satisfies the requirement pyside6>=6.5.1 (from khoj-assistant) (from versions: 6.0.0a1.dev1606911628, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.2.0, 6.2.1, 6.2.2, 6.2.2.1, 6.2.3, 6.2.4)
ERROR: No matching distribution found for pyside6>=6.5.1 (from khoj-assistant)
```

```
Description:	Ubuntu 20.04.6 LTS
5.19.17-051917-generic
Python 3.8.10

```
