### ISSUE TITLE
Consider adding repo-review badge to README

### ISSUE THREAD

**Issue by richardanderson001** [khoj-ai/khoj#401]
Thanks for creating this repo!

Would you be interested in adding a **review** badge to the README?

<a href='https://github.com/repo-reviews/repo-reviews.github.io/blob/main/create.md' target="_blank"><img alt='Github' src='https://img.shields.io/badge/review-100000?style=flat&logo=Github&logoColor=white&labelColor=888888&color=555555'/></a>

These help the open-source community collect and share UX stories via http://repo-reviews.github.io and thereby increase productivity, sponsorship, and cross-pollination on a global scale.

Happy to provide one in a PR!

**Comment by debanjum** [comment]
Hi, thanks for the suggestion. But I'd prefer folks to share feedback about Khoj on our Discord or Github discussions. This keeps the places we need to review/engage with the feedback maintainable

**Comment by richardanderson001** [comment]
Thanks, totally understand.

When someone writes a review, they are automatically prompted to submit an issue in the reviewed repo, thereby notifying the repo so any issues in it can be flagged.  However the purpose of reviews is not to flag issues, but share UX stories- for example:
- a repo could be working as intended, but might not be a suitable fit for a particular user, stack, or implementation
- a repo could be losing momentum, core team moved on, or have other development meta-issues that would be helpful sharing
- particularly critical issues are `wontfix` or `not planned` or on a long-term dev roadmap
- multiple repos could be attempting to achieve the same goal, the process of comparing repos can be very time-consuming, yet the venue for such a comparison does not lie within one of the reviewed repos (nor their issues or discussions)

In these cases, it can save a person hours if not days of work to read through reviews (I speak from personal experience, which is why I'm a fan).

I hope that helps to explain the goal of sharing UX stories in an independent, transparent, and centrally-located repo.  

Completely understand and respect your choice to close as not planned 👍
