### ISSUE TITLE
[feature request] txt file plugin

### ISSUE THREAD

**Issue by Gangxin-Li** [khoj-ai/khoj#416]
Hi Ai leaders,

After review your codes and project, I found it's a amazing project among the LLM filed, I have a suggestion about the features, is it possible to provide a txt file plugins? 

I believe this plugin is benefit for your project, and easy to implement.

**Comment by Ellen7ions** [comment]
Khoj does not support chatting with txt files. But PR #415 does support chatting with URLs, so you just need to set the URL of the txt file.

**Comment by sabaimran** [comment]
Hey @Gangxin-Li , I've been meaning to do this for a while with #237 . Maybe the time has finally come around now 😁
