### ISSUE TITLE
How to ensure Khoj is using GPU on device

### ISSUE THREAD

**Issue by mzeidhassan** [khoj-ai/khoj#418]
Hi team,
I am using "khoj_0.10.1_amd64.exe" at the moment, but it takes a long time to get responses during chat. 
Is there a way to ensure that Khoj is utilizing my GPU to speed up things a bit?

Thanks

**Comment by 1am** [comment]
It would be great to see how to increase. Using Khoj on i7 32GB Ram offline with llama-2-7b-chat.ggmlv3.q4_K_S.bin and it takes >200sec to get a response which could probably reduced. Still super happy about Khoj though :)

**Comment by sammcj** [comment]
I think Khoj might actually not support GPUs at all looking at https://github.com/khoj-ai/khoj/issues/388 and https://github.com/khoj-ai/khoj/issues/390

**Comment by Hunanbean-Collective** [comment]
that is unfortunate, considering LocalGPT works on CUDA already

**Comment by Hunanbean-Collective** [comment]
That makes it all pretty pointless.

**Comment by debanjum** [comment]
> That makes it all pretty pointless.

@Hunanbean-Collective please keep your comments constructive (and nice)

**Comment by Hunanbean-Collective** [comment]
That is meant as constructive. the point of use of the project is to keep
our private databases private.. unless i misunderstand, this is the exact
opposite of that.

**Comment by debanjum** [comment]
Thanks for clarifying your expectations. 
1. Khoj is meant to be a great open-source, personal AI copilot
2. Khoj being completely private is one of the options it supports but it is not the only one. For example, Khoj chat works with OpenAI's Chat model. The Khoj inference server will expose more powerful open-source models that cannot run on consumer hardware like the Llama 2 70B
4. Once the underlying dependencies gain GPU support for offline chat models, we'll add support for it in Khoj as well. See #494

**Comment by debanjum** [comment]
Closing this issue as Khoj uses GPU where GPU support is available by the underlying library used (GPT4All). This currently includes MacOS and now [Vulcan supported GPU + OS](https://vulkan.gpuinfo.org/) with #494
