### ISSUE TITLE
Mark the Obsidian plugin for Khoj as Desktop Only

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#421]
As title, Khoj is currently only supported in the Desktop environment, as it requires a connection to the host server that's surfacing the `/search` and `/chat` endpoints. Explicitly mark this as dekstop-only.

See further discussion [in this thread](https://discord.com/channels/1112065956647284756/1112066447947083826/1137852741637644308).

**Comment by Comprehensive-Jason** [comment]
#422 Done.
