### ISSUE TITLE
Not available over network

### ISSUE THREAD

**Issue by jenkshields** [khoj-ai/khoj#431]
Kia ora! I've just got Khoj set up on my home desktop and it's running fine there, but I'm having trouble accessing it from other devices. I have tailscale set up and my other services (*arr apps, mostly) are available over tailscale, but :42110 just times out, both through tailscale and directly over my local network.

Firewall is disabled, so I'm not sure what's blocking this connection!

Windows 11, attempting connection on iOS.

Edit: I think this is because Khoj is bound to localhost - I also can't access it via the computer's local ip on the computer itself. But I can't find where to change this!

**Comment by debanjum** [comment]
Great to know Khoj is running fine on your desktop!

> Edit: I think this is because Khoj is bound to localhost - I also can't access it via the computer's local ip on the computer itself. But I can't find where to change this!

Yes, to make khoj accessible over tailscale you'll need to expose it on your desktop's tailscale I.P by starting it from the terminal with 
```bash
 khoj --host <tailscale-ip-of-your-desktop>
```
You should then be able to access khoj from you iphone by opening `http://<tailscale-ip-of-your-desktop>:42110` in your iphone web browser

**Comment by debanjum** [comment]
Marking this issue as resolved. Please feel free to re-open if you're still not able to access your Khoj over the network.
