### ISSUE TITLE
Support Query Filters in Chat

### ISSUE THREAD

**Issue by debanjum** [khoj-ai/khoj#433]
Search already supports (file, date and word) query filters but Chat doesn't allow using these yet.

Supporting this will allow limiting Chat to respond using only entries that satisfy those query filters

**Comment by sabaimran** [comment]
This was added with https://github.com/khoj-ai/khoj/commit/01b310635e190cce0d04c92a21e2b8973216a302. I'm adding a couple of bug fixes to close it out.
