### ISSUE TITLE
Support customizing Q&A use cases

### ISSUE THREAD

**Issue by wenlzhang** [khoj-ai/khoj#434]
I can think of three use cases for now: chatting with own documents; continuous conversations with documents; and general chatting. For me, I am more interested in Q&A with own documents, which are the first two cases.

**Comment by debanjum** [comment]
Thanks for opening an issue to track this. We can add a command to limit Khoj to answer from your documents only. See the [discussion on discord](https://discord.com/channels/1112065956647284756/1112069753549373480/1138990372110991480)

**Comment by debanjum** [comment]
This was resolved in #463. Using `/notes` prefix in your messages should limit Khoj to only respond using your documents as reference. See [docs](https://docs.khoj.dev/#/chat?id=commands) for reference
