### ISSUE TITLE
Installation of khoj Backend under Big Sur as its launch results in the same error message

### ISSUE THREAD

**Issue by fdarnel** [khoj-ai/khoj#435]
macOS 11.7.9, MacBook Intel, Python 3.11 (python.org). Trying to install then lauch Backend to use with Obsidian plugin.
Installation and lauch end with :
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllmodel.dylib, 6): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllmodel.dylib (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib

**Comment by debanjum** [comment]
That's unfortunate. Seems like the package is expecting c++ installed in a specific place (`/usr/lib/libc++.1.dylib`). Can you confirm:
* Which pytorch version do you have installed on your system? It should be >= 1.6.0 based on [this comment](https://github.com/pytorch/pytorch/issues/36941#issuecomment-617359369) 
  You can upgrade it by running `pip install --upgrade torch` in your terminal
* Does the `/usr/lib/libc++.1.dylib` file exist? If so, can you try install the Khoj backend in a python virtual environment
   ```bash
   python -m venv .venv && source .venv\bin\activate
   pip install khoj-assistant
   cp /usr/lib/libc++.1.dylib .venv/lib/python3.11/site-packages/torch/lib # the suggested fix
   khoj
   ```
* Is `xcode` installed on your Mac? You can install it by running `xcode-select --install` on your terminal

**Comment by debanjum** [comment]
Closing issue due to lack of details to reproduce bug and issue having gone stale
