### ISSUE TITLE
Markdown contents

### ISSUE THREAD

**Issue by Gangxin-Li** [khoj-ai/khoj#445]
Hi folks, 

When I used KHOJ to write some code, I found that it doesn't have a markdown format to highlight the code. Do you have any ideas on how to implement that?

<img width="1460" alt="Screenshot 2023-08-16 142103" src="https://github.com/khoj-ai/khoj/assets/105022948/672f3480-d9df-41de-848a-06ec99284150">
<img width="1593" alt="Screenshot 2023-08-16 142131" src="https://github.com/khoj-ai/khoj/assets/105022948/35a98d4f-689b-4e0d-90fe-7bb2842be8a4">

**Comment by sabaimran** [comment]
Fair point @Gangxin-Li. Are you using LlamaV2 here? I want to caveat here that I think that llamaV2 won't work _as well_ with formatting programmatic output (it has to come with the triple backticks ("```"). This would work well for GPT4.

That being said, I'll push a change to the front-end code here to support formatting!

**Comment by sabaimran** [comment]
Noting here: to use the clipboard, you'll have to set the host in your machine to `localhost` or `127.0.0.1`, as opposed to `0.0.0.0`, for instance.

**Comment by Gangxin-Li** [comment]
Yes, I am using the LlamaV2. Looking forward to your new feature. 
Yes, I am using the 127.0.0.1, thanks for your check.
