### ISSUE TITLE
core dumping

### ISSUE THREAD

**Issue by digitalw00t** [khoj-ai/khoj#455]
I'm running on my laptop from the deb package I just downloaded.  I go to the menu, click the khoj icon, a lantern icon appears momentarily for abou 30-45 seconds, core dump happens and it's all over with nothing reallyh to show for it.  Hope this helps.

Aug 21 14:48:38 sumomo systemd-coredump[20753]: Process 20719 (Khoj) of user 1000 dumped core.#012#012Found module /tmp/_MEI6CwCPv/PySide6/QtPrintSupport.abi3.so without build-id.#012Found module /tmp/_MEI6CwCPv/PySide6/QtWebEngineCore.abi3.so without buil
d-id.#012Found module /tmp/_MEI6CwCPv/PySide6/QtNetwork.abi3.so without build-id.#012Found module /tmp/_MEI6CwCPv/libxshmfence.so.1 with build-id: 2f059343453436272930d81557a2f5d7db5fb4cb#012Found module /tmp/_MEI6CwCPv/libk5crypto.so.3 with build-id: f77b9cc59d0814c9cc6e47c83c9995a102702d8b#012Found module /tmp/_MEI6CwCPv/libkrb5.so.3 with build-id: 61b74ac570e86bf5e85f095823d891d5c3bc7cfd#012Found module /tmp/_MEI6CwCPv/libgssapi_krb5.so.2 with build-id: ea18178b08e8b7e057a08a199c8a63ce1dc7b991#012Found module /tmp/_MEI6CwCPv/libxkbfile.so.1 with build-id: 01781f63144a19db82d59fc88c8e61fda45c166a#012Found module /tmp/_MEI6CwCPv/libXtst.so.6 with build-id: f5b91f39bffeba7770712f5876e162593784d92c#012Found module /tmp/_MEI6CwCPv/libasound.so.2 with build-id: 592833f648d7ba3b745ecf114986ee2029094986#012Found module /tmp/_MEI6CwCPv/libnspr4.so with build-id: 3a3f31d4d3edfcbcb6356a36a92bb55c98eb121f#012Found module /tmp/_MEI6CwCPv/libnssutil3.so with build-id: 04303308175b1a4d5b3425a7543d10e2a322c01e#012Found module /tmp/_MEI6CwCPv/libnss3.so with build-id: 53f5a8a185db3abf260b77ea560179a395b892e0#012Found module /tmp/_MEI6CwCPv/libsmime3.so with build-id: 1a2d8891f02cdb22aee9b1ceaef4a6d32ca083df#012Found module /tmp/_MEI6CwCPv/libQt6Positioning.so.6 with build-id: 39e8ab1700c96ba1453baa10b7e396d9a93771af#012Found module /tmp/_MEI6CwCPv/libQt6OpenGL.so.6 with build-id: 8c9c9e774288379cf7b1c733d455ddf7a0ade592#012Found module /tmp/_MEI6CwCPv/libQt6Network.so.6 with build-id: a168fb598a92ff23fca4413c681e2113ed9c1495#012Found module /tmp/_MEI6CwCPv/libQt6Qml.so.6 with build-id: 21748cdbb16c96e87ea1e693fdba424f15b5be52#012Found module /tmp/_MEI6CwCPv/libQt6QmlModels.so.6 with build-id: 4d993f30a0f89aa126c38979204db8c8de0275bf#012Found module /tmp/_MEI6CwCPv/libQt6Quick.so.6 with build-id: c90876969bca820e9d477b8bd43da910a698b9fe#012Found module /tmp/_MEI6CwCPv/libQt6WebChannel.so.6 with build-id: f3be287abbdb23cc32ef6dcdc91b14f0cff82168#012Found module /tmp/_MEI6CwCPv/libQt6WebEngineCore.so.6 with build-id: 2428600178dd028ade4b7938a2eeab87211c4cfc#012Found module /tmp/_MEI6CwCPv/libQt6PrintSupport.so.6 with build-id: 6db5bfbbfb48ada93a3c0de3237266386db70484#012Found module /tmp/_MEI6CwCPv/PySide6/QtCore.abi3.so without build-id.#012Found module /tmp/_MEI6CwCPv/PySide6/QtGui.abi3.so without build-id.#012Found module /tmp/_MEI6CwCPv/libgcrypt.so.20 with build-id: b48501d59ed1a1c1ff29d3e68aecd831b613a23c#012Found module /tmp/_MEI6CwCPv/libicudata.so.56 with build-id: 34aac32bb4d3c0f44e72e57cf253a871240a1154#012Found module /tmp/_MEI6CwCPv/libicuuc.so.56 with build-id: 80916a3578c4abf8d9433986b7ca87ee58797eb5#012Found module /tmp/_MEI6CwCPv/libicui18n.so.56 with build-id: ea6a2369dae8e186543b5e0fa413cb7ee7058c84#012Found module /tmp/_MEI6CwCPv/libQt6Core.so.6 with build-id: 098b975371758029c26c24fc2a3b216b1a01b019#012Found module /tmp/_MEI6CwCPv/libQt6Gui.so.6 with build-id: e466b4257c5c66f38d8306cd56a7870ed3fa2ac3#012Found module /tmp/_MEI6CwCPv/libQt6Widgets.so.6 with build-id: 94d6936a9006809d00fd2ef3a6f028bf98bd18b1#012Found module /tmp/_MEI6CwCPv/PySide6/QtWidgets.abi3.so without build-id.#012Found module /tmp/_MEI6CwCPv/libXau-154567c4.so.6.0.0 without build-id.#012Found module /tmp/_MEI6CwCPv/libQt6WebEngineWidgets.so.6 with build-id: f23463388f2f37d5a2c2a3786e596648d560b5f1#012Found module /tmp/_MEI6CwCPv/libsystemd.so.0 with build-id: f949edcd5da116ad1f264107c520c6c5fbf97397#012Found module /tmp/_MEI6CwCPv/libdbus-1.so.3 with build-id: fbbb3cfb1351ae4879456a851397ef94be8339a7#012Found module /tmp/_MEI6CwCPv/libpcre-9513aab5.so.1.2.0 without build-id.#012Found module /tmp/_MEI6CwCPv/PySide6/QtWebChannel.abi3.so with build-id: 7cf4fc2fd747a3a39206fbb29148be77cb0dc8da#012Found module /tmp/_MEI6CwCPv/libQt6DBus.so.6 with build-id: 667c50bee75c463f4228f38ae0f526ce2ea631e6#012Found module /tmp/_MEI6CwCPv/libselinux-0922c95c.so.1 without build-id.#012Found module /tmp/_MEI6CwCPv/PySide6/QtWebEngineWidgets.abi3.so without build-id.#012Found module /tmp/_MEI6CwCPv/libpcre.so.3 with build-id: cef782225a118af34a28083235a6da2aa59b7e82#012Found module /tmp/_MEI6CwCPv/libglib-2.0.so.0 with build-id: 5fdb313daf182a33a858ba2cc945211b11d34561#012Found module /tmp/_MEI6CwCPv/libkeyutils-dfe70bd6.so.1.5 without build-id.#012Found module /tmp/_MEI6CwCPv/libxkbcommon.so.0 with build-id: 09844610cc38154fd3610e18dcccec67e5bbebf1#012Found module /tmp/_MEI6CwCPv/libpyside6.abi3.so.6.5 without build-id.#012Found module /tmp/_MEI6CwCPv/libshiboken6.abi3.so.6.5 without build-id.#012Found module /tmp/_MEI6CwCPv/libkrb5support-d0bcff84.so.0.1 without build-id.#012Found module /tmp/_MEI6CwCPv/libgpg-error.so.0 with build-id: 8d5a01acc26f61ca3aa6aa4ec14ec9712234d153#012Found module /tmp/_MEI6CwCPv/libk5crypto-b1f99d5c.so.3.1 without build-id.#012Found module /tmp/_MEI6CwCPv/libcom_err-2abe824b.so.2.1 without build-id.#012Found module /tmp/_MEI6CwCPv/libkrb5-fcafa220.so.3.3 without build-id.#012Found module /tmp/_MEI6CwCPv/libXi.so.6 with build-id: 589c42ad0b0e40a25e44f26f0f9eb88ea6760c5e#012Found module /tmp/_MEI6CwCPv/liblzma-c1d09604.so.5.2.7 without build-id.#012Found module /tmp/_MEI6CwCPv/libgssapi_krb5-497db0c6.so.2.2 without build-id.#012Found module /tmp/_MEI6CwCPv/libkrb5support.so.0 with build-id: bdbcaa139843b1b8f4091faa67ee3f1d1c22fec3#012Found module /tmp/_MEI6CwCPv/libXrandr.so.2 with build-id: f6537f24d2b40458410cba6e27aca22160f67865#012Found module /tmp/_MEI6CwCPv/libxcb-07618c2c.so.1.1.0 without build-id.#012Found module /tmp/_MEI6CwCPv/libtiff-e8d4c6df.so.5.8.0 without build-id.#012Found module /tmp/_MEI6CwCPv/libjpeg-1678c144.so.62.3.0 without build-id.#012Found module /tmp/_MEI6CwCPv/libcrypto-d3570994.so.1.0.2k without build-id.#012Found module /tmp/_MEI6CwCPv/libkeyutils.so.1 with build-id: 92bfbdffd7504f6bc931733e214e475e3f71ce3a#012Found module /tmp/_MEI6CwCPv/libopenjp2-8fa4ced9.so.2.5.0 without build-id.#012Found module /tmp/_MEI6CwCPv/PIL/_imaging.cpython-39-x86_64-linux-gnu.so with build-id: 0abadcccbf59d6c9b39f742812523a1d938d3125#012Found module /tmp/_MEI6CwCPv/libssl-cd1d6220.so.1.0.2k without build-id.#012Found module /tmp/_MEI6CwCPv/liblz4.so.1 with build-id: f64a53f0f288938d86782cc5547c0ed71063ba3f#012Found module /tmp/_MEI6CwCPv/tokenizers/tokenizers.cpython-39-x86_64-linux-gnu.so without build-id.#012Found module /tmp/_MEI6CwCPv/numexpr/interpreter.cpython-39-x86_64-linux-gnu.so with build-id: d95db658fff2ca713c36533e6590f8d95b4d4b5c#012Found module /tmp/_MEI6CwCPv/greenlet/_greenlet.cpython-39-x86_64-linux-gnu.so with build-id: bd5034220f36cf9f35f51ed59cac6945832599cb#012Found module /tmp/_MEI6CwCPv/sqlalchemy/cyextension/collections.cpython-39-x86_64-linux-gnu.so with build-id: 0e82ea1565bd135ceedd9400a2766cccd7da210a#012Found module /tmp/_MEI6CwCPv/aiohttp/_http_parser.cpython-39-x86_64-linux-gnu.so with build-id: 0968502acb4effcedd5f44ee637efff619c4f567#012Found module /tmp/_MEI6CwCPv/nvfuser/_C.cpython-39-x86_64-linux-gnu.so with build-id: a9bcb07999a1c57141df7a5beaf5c6b49577409f#012Found module /tmp/_MEI6CwCPv/libnvrtc.so.11.2 without build-id.#012Found module /tmp/_MEI6CwCPv/libQt6QuickWidgets.so.6 with build-id: be1dbb5e955788e037b9edc623f88c88d2de3e96#012Found module /tmp/_MEI6CwCPv/libnvfuser_codegen.so without build-id.#012Found module /tmp/_MEI6CwCPv/libnccl.so.2 with build-id: 613aeb0629dd2e28e0f6ca8581c2b6cb7e49b466#012Found module /tmp/_MEI6CwCPv/libcom_err.so.2 with build-id: bb8645b8abf4a687b3c5ec868fbd72583985b0b5#012Found module /tmp/_MEI6CwCPv/libcusparse.so.11 with build-id: 4434e9c0e77f706bda143c3cfd45247c30cdf770#012Found module /tmp/_MEI6CwCPv/libXfixes.so.3 with build-id: 38eecbcccea120c9ed550279c14d458aa2cfee3b#012Found module /tmp/_MEI6CwCPv/libcupti.so.11.7 without build-id.#012Found module /tmp/_MEI6CwCPv/libcudnn.so.8 with build-id: 31fa9c90290cd2f4ee20087fb78
Aug 21 14:48:38 sumomo systemd[1]: systemd-coredump@2-20752-0.service: Deactivated successfully.
Aug 21 14:48:38 sumomo systemd[1]: systemd-coredump@2-20752-0.service: Consumed 7.008s CPU time.
Aug 21 14:48:39 sumomo systemd[1]: Started Process Core Dump (PID 20824/UID 0).
Aug 21 14:48:39 sumomo systemd-coredump[20825]: Process 20703 (Khoj) of user 1000 dumped core.#012#012Found module linux-vdso.so.1 with build-id: 94f2c4c5b8fcb5a63866a943b8a321ac1458b921#012Found module libgcc_s.so.1 with build-id: e3a44e0da9c6e835d293ed8fd2882b4c4a87130c#012Found module ld-linux-x86-64.so.2 with build-id: 61ef896a699bb1c2e4e231642b2e1688b2f1a61e#012Found module libc.so.6 with build-id: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d#012Found module libpthread.so.0 with build-id: e62798b68557abb4bc5548aba2640cd5ab948f36#012Found module libz.so.1 with build-id: 30840b79ac329ecbf1dec0bb60180eed256d319f#012Found module libdl.so.2 with build-id: 952123c3bdce7c3370553717942b4878d1fad797#012Found module Khoj with build-id: 0230dd29d2f5ba42b3274ff7981105c752577832#012Stack trace of thread 20703:#012#0  0x00007fb26889ba7c __pthread_kill_implementation (libc.so.6 + 0x96a7c)#012#1  0x00007fb268847476 __GI_raise (libc.so.6 + 0x42476)#012#2  0x000000000040414a n/a (Khoj + 0x414a)#012#3  0x00007fb26882ed90 __libc_start_call_main (libc.so.6 + 0x29d90)#012#4  0x00007fb26882ee40 __libc_start_main_impl (libc.so.6 + 0x29e40)#012#5  0x000000000040256e n/a (Khoj + 0x256e)
Aug 21 14:48:39 sumomo systemd[1]: systemd-coredump@3-20824-0.service: Deactivated successfully.

**Comment by debanjum** [comment]
Ouch. Which version of the Khoj desktop app did you try install? [Khoj 0.11.0](https://github.com/khoj-ai/khoj/releases/tag/0.11.1) removed it's dependency on PyQtWebEngine. But the below error suggests Khoj is crashing because it's missing PyQtWebEngine dependencies.

> Found module /tmp/_MEI6CwCPv/PySide6/QtPrintSupport.abi3.so without build-id.#012Found module /tmp/_MEI6CwCPv/PySide6/QtWebEngineCore.abi3.so without buil

**Comment by digitalw00t** [comment]
I pulled the deb from the website 2 days ago.. so version 0.11.0

```
ii  khoj                                       0.11.0                                     amd64        no description given
```

**Comment by debanjum** [comment]
I see. Strange that the stacktrace still mentions PtQtWebEngine. 

Can you share details of the OS you're running Khoj on? I'll try and reproduce the issue on my end.

**Comment by digitalw00t** [comment]
OS: Linux Mint 21.1 x86_64 
Host: Latitude 7410 
Kernel: 5.15.0-79-generic 
Uptime: 18 hours, 11 mins 
Packages: 2906 (dpkg), 16 (flatpak), 10 (snap) 
Shell: bash 5.1.16 
Resolution: 1920x1080 
DE: Cinnamon 5.6.8 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark-Aqua (Mint-Y) 
Theme: Mint-Y-Aqua [GTK2/3] 
Icons: Mint-Y-Aqua [GTK2/3] 
Terminal: SecureCRT 
CPU: Intel i7-10610U (8) @ 4.900GHz 
GPU: Intel CometLake-U GT2 [UHD Graphics] 
Memory: 10782MiB / 15658MiB

**Comment by debanjum** [comment]
This issue is stale now. We've deprecated the old Khoj desktop app and moved from QT to Electron in [Release 0.12.2](https://github.com/khoj-ai/khoj/releases/tag/0.12.2)
