### ISSUE TITLE
Will not work offline. 

### ISSUE THREAD

**Issue by Hunanbean-Collective** [khoj-ai/khoj#458]
khoj will not work offline. if it cannot contact    `tcp6://2600:9000:24ba:1800:17:b174:6d00:93a1`  it will not work.
if you attempt it, then reconnect to the net and restart kohj, it will re-download the chat model, overwriting the same chat model that is already cached.

I consider this a **Severe issue**

everything fully installed and running fine. shut down khoj. unplug internet cable. restart kohj. watch it all fall apart.

**Comment by sabaimran** [comment]
hey @Hunanbean-Collective , I think this is related to https://github.com/khoj-ai/khoj/issues/450. It should be fixed now -- feel free to try it by downloading the pre-release, with `pip install --pre khoj-assistant`.

**Comment by Hunanbean-Collective** [comment]
I did not install through python. I am just using the release .exe. Glad it was already known and being worked on. Thanks

**Comment by sabaimran** [comment]
Sweet, then it should be available with the next release. We'll build new images for the `.exe` file.
