### ISSUE TITLE
Experiment with Llama prompts so that it understands it has access to personal information

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#461]
LlamaV2 is extremely tuned to believe it cannot do anything unethical, including access personal data of users. 
To by pass this limitation, experiment further with the prompts to help it be sure that yes, it does have access to a limited set of personal data.

[link to relevant discussion](https://discord.com/channels/1112065956647284756/1112065956647284759/1144305156603789392)

**Comment by kroonen** [comment]
Does it works with LLaMa model? There are variation available on hugging face like OpenOrca for instance : https://huggingface.co/kroonen/OpenOrca-Platypus2-13B-GGUF

**Comment by debanjum** [comment]
Thanks for the reference, @kroonen! Less censored models of Llama2 needs to be tested for not being too prudeish. We haven't done that yet

**Comment by sabaimran** [comment]
See also [this discussion](https://discord.com/channels/1112065956647284756/1155215909804314624/1157065256959496232) regarding prompt syntax leakage. Happens occasionally, sporadically.
