### ISSUE TITLE
Allow configuration to search subfolders

### ISSUE THREAD

**Issue by piebaker** [khoj-ai/khoj#465]
When using a folder-based obsidian setup, Khoj will not search subfolders (on windows) for .md files. 
This results in a static set of folders it can search, as any new subfolders created are not searched for new .md files. 
It also means on install setup the user may have to organise many folders to create a folderset to search

**Comment by piebaker** [comment]
Closed due to user stupidity lol

**Comment by sabaimran** [comment]
lol hey @piebaker , did you see some issue that led you to think it wasn't indexing subfolders? We can always think of ways to make the UX more intuitive.

**Comment by piebaker** [comment]
Yeah, found #208 lol
I initially was following the Windows setup instructions on the wiki, not knowing I needed to follow the specific obsidian instructions. 
It might be worth merging the "Interfaces" section into the actual install section, as (aside from the web page) both emacs & obsidian are also install guides for their specific versions, and when a user wants to get up and going the first step is usually to install the program, not the setup its UI (as that is what the interface section implied IMO)

**Comment by sabaimran** [comment]
Ah fair point, we should probably reword the pointers here. Interface implies it's just UI, rather than configuring the entire client. Thanks for the feedback!
