### ISSUE TITLE
Create a new desktop client

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#470]
Use a framework like electron, tauri, or something else to create a desktop client that can effectively act as a syncing agent for local files to the backend server and allow users to manage their credentials (sign in, create an account).

Ideally we should also setup an easier mechanism for signing. Refer to ToDesktop: https://www.todesktop.com/electron

**Comment by wyenelle** [comment]
From the above instruction, you need a web app developerd with a framework that looks like what todesktop has already ?

**Comment by sabaimran** [comment]
@wyenelle , yeah! I was able to try out the ToDesktop workflow and it works pretty well for our use case. Adding it in this PR: https://github.com/khoj-ai/khoj/pull/473

**Comment by wyenelle** [comment]
Must it be done with electron

**Comment by sabaimran** [comment]
@wyenelle yes, or any desktop framework that allows us to run processes outside of the browser. Using a Go/Wails app could have been another alternative, but would be a steeper learning curve.

**Comment by wyenelle** [comment]
I'm a front-end developer with React. Is there any way I can come in. I'm new to open source

**Comment by sabaimran** [comment]
hey @wyenelle , happy to hear you're interested in working on Khoj! can you hop in our Discord, where we can continue the discussion? feel free to grab a contributor role: https://discord.gg/BDgyabRM6e

We're not currently planning on integrating React in the front-end as it's just not necessary and makes the build setup a little more complicated, but may do this as the UX becomes more complex.

**Comment by wyenelle** [comment]
Thanks 
I just joined the Discord channel . Looking forward to contributing
