### ISSUE TITLE
UnicodeDecodeError: 'cp949' codec can't decode byte 0x80 in position 97: illegal multibyte sequence

### ISSUE THREAD

**Issue by goodasa** [khoj-ai/khoj#472]
Hi,

I am CHOI and I want to bring up a matter about Korean.

Khoj can't index my org files because I organize them in Korean.

I faced the same problem while using Org-roam for the first time, but it was resolved through updates.

I'm looking forward to this issue being resolved soon.

Thank you.

**Comment by debanjum** [comment]
Hi CHOI, are you on a windows machine and are your org files encoded as utf-8? I've pushed a fix for the issue. Feel free to reopen this issue if the problem persists after upgrading to the latest Khoj
