### ISSUE TITLE
Obsidian says 0.12.1 update avail but 0.12.0 latest published version

### ISSUE THREAD

**Issue by luckman212** [khoj-ai/khoj#486]
Seems to be a typo somewhere!

<img width="394" alt="image" src="https://github.com/khoj-ai/khoj/assets/1992842/4342b6ea-1a27-4e58-a589-c137b64d8585">

<img width="561" alt="image" src="https://github.com/khoj-ai/khoj/assets/1992842/d3933a16-cb9b-4bf5-a5b8-ca26dbf418cd">

**Comment by sabaimran** [comment]
Should be resolved now! We had a bad release in between.
