### ISSUE TITLE
Feature Request: Add support for using local llms

### ISSUE THREAD

**Issue by arian81** [khoj-ai/khoj#501]
It's very easy to spin up a local llm and get an endpoint using ollama (https://ollama.ai/). I think that should be a feature supported by khoj. You can easily use langchain wrapper for Ollama to call local endpoints.

**Comment by debanjum** [comment]
I've just added support for running [any GPT4All supported model](https://github.com/nomic-ai/gpt4all/blob/main/gpt4all-chat/metadata/models.json) in #494. You can try it with `pip install --upgrade --pre khoj-assistant`. 

We'll add support for using other chat LLMs servers which expose an OpenAI style API interface (like local.ai, text-generation-webui etc.) once #407 is implemented. 

I'll close this issue for now. But feel free to re-open it if you have other concerns

**Comment by lrq3000** [comment]
GPT4All supports many more models than their [list of curated models](https://github.com/nomic-ai/gpt4all/blob/main/gpt4all-chat/metadata/models.json), such as dolphin-mistral. Is there a way to use custom models? Can I specify a path, or do I need to copy the model to `C:\Users\<username>\.cache\gpt4all` ?

**Comment by debanjum** [comment]
You can update your `chat-model`offline-chat > chat-model` `khoj.yml` file (usually at `~/.khoj/khoj.yml`) to

**Comment by debanjum** [comment]
You can update the `chat-model` field under `processor > conversation > offline-chat` section in your `khoj.yml` file at `~/.khoj/khoj.yml` to any supported GPT4All chat model.

Current limitations of this our that we only use the llama2 prompt template. But different chat models expect different chat templates. We'll add support for custom chat templates in a little while once we're done with current Khoj rearchitecture work to add multi-user support

**Comment by lrq3000** [comment]
Ok I understand, you are working at a truly impressive speed! Thank you so very much! I wish you lots of success with your project!

**Comment by yinzixie** [comment]
Hmm, I'm not sure why I only find a log file under the `/root/.khoj` folder.  I am using docker compose.

**Comment by debanjum** [comment]
> Hmm, I'm not sure why I only find a log file under the `/root/.khoj` folder. I am using docker compose.

Hi @yinzixie, please see the [khoj docs](https://docs.khoj.dev/get-started/setup) to [configure khoj chat models](https://docs.khoj.dev/get-started/setup#3-configure) etc. Khoj has been rearchitected to use postgres DB for configuration instead of the previous `khoj.yml` config file
