### ISSUE TITLE
Index data in SQLite DB

### ISSUE THREAD

**Issue by Victor239** [khoj-ai/khoj#504]
Would love to see this be able to work on data stored in SQLite too.

**Comment by sabaimran** [comment]
Neat idea! @Victor239 , do you mind sharing more about your use case? What kind of data would you want to search on?

**Comment by Victor239** [comment]
There are some smaller apps I'd like to use it with but mainly because Logseq (an app which has been mentioned elsewhere on this GitHub) is getting a [database](https://github.com/logseq/logseq/pull/9858) mode, so I'd love to use it with that.

**Comment by sabaimran** [comment]
Do you imagine you would want something that dynamically infers which (presumably text) columns to index? Or, would you want to be able to configure the column names that should be indexed?

You've also reminded me that I've been wanting to apply Khoj to my Signal sqlite database. Might be a fun place to experiment with feature development.

**Comment by Victor239** [comment]
Dynamically infers ideally, but I can imagine a later feature to add for advanced users would allow choosing which columns to utilise.

**Comment by sabaimran** [comment]
We don't have db integrations in scope right now. I'll close this as not planned for the moment, but definitely feel free to create a plugin integration that can be used to push data to the indexer endpoint?
