### ISSUE TITLE
QUESTION: Documentation on windows installation

### ISSUE THREAD

**Issue by eskayML** [khoj-ai/khoj#507]
I'm not sure if this is the right place to ask this, but on the documentation, i needed to install an exe file from the releases page, i couldn't find any .exe file there .

![image](https://github.com/khoj-ai/khoj/assets/71832907/76aaa89f-bd5e-4349-b0eb-026752ba33b5)

Would love if someone can help me with further directions

**Comment by sabaimran** [comment]
Hi @eskayML! Sorry for the confusion. It seems you've reached that page via [1.4 Use (deprecated) desktop builds](https://docs.khoj.dev/#/setup?id=_14-use-deprecated-desktop-builds)

I just wanted to reiterate and say that those instructions are only for our deprecated installations, and you'll only find them in releases before `0.12.0`. For example, see the release for [0.11.2](https://github.com/khoj-ai/khoj/releases/tag/0.11.2) - you'll find the exe file in the assets. 

If you want to use our _new_ clients, you can click on https://download.khoj.dev and a download of the latest Windows app should automatically start. It tries to intelligently find the correct download for your OS automatically. You can also download it manually using the assets in this release: https://github.com/khoj-ai/khoj/releases/tag/0.13.0 (see the .exe file).
