### ISSUE TITLE
Incompatible with Python 3.12

### ISSUE THREAD

**Issue by lrq3000** [khoj-ai/khoj#522]
Just to let you guys know that the pre-release/github version of `khoj-assistant` (hash https://github.com/khoj-ai/khoj/commit/9677eae79192aed2171a433f4ae4d9adff7afba1) is currently incompatible with Python 3.12 because of two issues:

1. `pyproject.toml` requires `pyyaml==6.0`, which causes an `AttributeError: cython_sources` as described [here](https://github.com/yaml/pyyaml/issues/724). Updating the requirement to `pyyaml>=6.0` or using Python 3.11 without changing this requirement fixes this issue.
2. `torch` requirement does not yet offer builds for Python 3.12, the latest supported version is Python 3.11. This issue cannot be fixed [currently](https://stackoverflow.com/questions/77225812/is-there-a-way-to-install-pytorch-on-python-3-12-0) (as of October 2023).

So there is nothing to do but wait, I am just reporting this issue in case others get the same error.

**Comment by sabaimran** [comment]
Thank you for reporting, @lrq3000 ! Updating `pyyaml` should be trivial, but `torch` might be trickier. We'll watch out for this.

**Comment by ststudio907** [comment]
I'm very new to python. Literally just got it to use khoj with obsidian. How do I update requirements, or downgrade to python 3.11?

**Comment by lrq3000** [comment]
@ststudio907 As long as you can't see a "cp312" package [here](https://download.pytorch.org/whl/torch/), pytorch is not available for py3.12 and hence py<=3.11 is required.

An easy way to get py3.11 or any othes version is to install a miniconda distribution with python 3.11, or if you already have it, create an environment under python 3.11.

**Comment by debanjum** [comment]
Thanks for the initial investigation @lrq3000. Khoj should support python 3.12 once PR #690 is merged. This got unblocked since Pytorch [added support for python 3.12](https://github.com/pytorch/pytorch/issues/110436) in [mainline version 2.2.2](https://download.pytorch.org/whl/torch/).

**Comment by lrq3000** [comment]
That's great to hear, thank you for the heads up!
