### ISSUE TITLE
Feature request: Ability to clear chat

### ISSUE THREAD

**Issue by tuan3w** [khoj-ai/khoj#523]
I use khoj plugin in Obsidian. And many time, I want to clear the current chat session. I know I can delete `conversation.json` to clear chat history. However, I think it would be helpful to have a button to clear chat history explicitly. Thanks.

**Comment by sabaimran** [comment]
@tuan3w , do you think your pain point would be mitigated if you were able to manage multiple sessions, and therefore separate context? Or is it important for you to have ephemeral/scratchpad conversations?

**Comment by liflovs** [comment]
Nice to see it fixed! Would wait for next release :) Just got here in search for solution
