### ISSUE TITLE
I cannot log in through a Google account

### ISSUE THREAD

**Issue by Carrie999** [khoj-ai/khoj#555]
I cannot log in through a Google account，it Jump Link https://app.khoj.dev/auth/redirect  and I saw   Internal Server Error on the screen，it returns 500

**Comment by debanjum** [comment]
Hi @Carrie999, thanks for raising this issue. I've moved the issue into the khoj repository from [flint](https://github.com/khoj-ai/flint). Saba's pushed a fix for it in 237195e. So you should be able to login now. Please feel free to re-open this issue if you still can't login
