### ISSUE TITLE
Add a health check to Khoj

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#570]
In `api.py`, add a simple `/health` endpoint that simply returns `200`.

**Comment by Sanket-Arekar** [comment]
Hey @sabaimran I would like to work on this issue. Can you Please assign me this issue?

**Comment by sabaimran** [comment]
Awesome! Thanks for volunteering, @Sanket-Arekar . Let me know if you need any guidance with the dev setup.

I would recommend cloning the repository, creating a virtual environment, and then running `pip install -e '.[dev]` to get started. We also need to add better documentation for this.

**Comment by Sanket-Arekar** [comment]
Okay. Thank You for assigning me this issue, I will start working on it.

**Comment by ayushjha119** [comment]
@sabaimran please check now, i have raised new PR according to your requirement

**Comment by sabaimran** [comment]
Thank for taking care of this @ayushjha119 ! I'm updating the developer documentation based on your experience in this PR: https://github.com/khoj-ai/khoj/pull/596. Let me know if there's anything you'd like to add.

**Comment by ayushjha119** [comment]
@sabaimran Thank you soo much, for helping in my first Open source contribution
