### ISSUE TITLE
[Bug] Cannot Use Khoj in Obsidian

### ISSUE THREAD

**Issue by tuan3w** [khoj-ai/khoj#581]
After update to new version, it seems like I cannot use Khoj anymore in Obsidian. I use khoj with anonymous mode:

```bash
khoj --anonymous-mode 
```

When I try to reindex data in Obsidian, I got bad request. It seems like the API has changed. I have already set API token.

Thanks.

**Comment by sabaimran** [comment]
@tuan3w , have you updated the version of your Khoj plugin in Obsidian? We have changed the API scheme in between, so it's best to make sure that your server version and client version are the same.

**Comment by tuan3w** [comment]
@sabaimran 

Yes. I'm using the latest version. I dig a little into the problem. It seems like the problem is that there is default 1000 files limit in starlette 0.25.0. 

Issue is reported here in FastAPI: https://github.com/tiangolo/fastapi/discussions/9634

So this problem is related https://github.com/khoj-ai/khoj/issues/573

**Comment by debanjum** [comment]
Thanks for the investigation and update @tuan3w! I'll close this issue and we can track the 1000 file limit issue separately.
