### ISSUE TITLE
docer dont run on my system

### ISSUE THREAD

**Issue by kalle07** [khoj-ai/khoj#599]
Why you need this  ALL realy ALL other programs here on git like LLMs and Img2Img dont need that ?!?

is that an windows internal WSL secure check ... i have bloked all  S H I T windows   : D

**Comment by debanjum** [comment]
It's unclear what this issue is about.

We use Docker to simply maintenance and setup of Khoj in our cloud and user machines.

For non developers, we recommend using the [khoj cloud service](https://app.khoj.dev/).
