### ISSUE TITLE
Create different contexts for different files and folders

### ISSUE THREAD

**Issue by oyarsa** [khoj-ai/khoj#672]
Thank you for creating Khoj! It works very well for searching my Markdown notes, but I'd like to use it for other things. For example, I have a folder full of research papers, and it would be great to search them. However, I don't want to import them into the same context as my personal notes because that would create too many conflicts and false positives.

It would be interesting to have different contexts or projects with different documents and folders enabled.

**Comment by debanjum** [comment]
Hey @oyarsa, thanks for the suggestion! Saba is working on the agent feature (see #671). It will allow you to talk to specific agents in a specific conversation sessions. A future iteration of it will add the ability to limit the files/folders an agent has access to. So you can separate chat session into specific contexts (e.g research agent with access to work notes, therapy agent with access to your journal etc.)

Does that match what you were requesting?

**Comment by oyarsa** [comment]
> So you can separate chat session into specific contexts (e.g research agent with access to work notes, therapy agent with access to your journal etc.)

This is precisely what I'm requesting. Thank you. I'm closing this issue and subscribing to the PR for future updates.

**Comment by sabaimran** [comment]
Hi @oyarsa ! If you don't mind, I'll keep the issue open until we've finally merged the full feature update. Looking forward to properly closing it out and getting your feedback 🙂.

**Comment by sabaimran** [comment]
Closed with #773, #788
