### ISSUE TITLE
Make three dot menu on conversation session persistent after it's clicked

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#699]
After the three dot menu is clicked once, it collapses again if the user hovers outside of the div range. Make it so that it stays open once the user has clicked.

Bonus: when a user scrolls in the sessions pane, a nav bar shows up which makes it hard to click on the three dot menu again. Fix the UI so as to avoid this problem.

**Comment by anudeepadi** [comment]
Can I work on it? @sabaimran

**Comment by debanjum** [comment]
Thanks @anudeepadi, that'd be great! Let us know if you need any help in testing these changes out?

**Comment by syrok94** [comment]
hey @debanjum, can I work on this issue?

**Comment by sabaimran** [comment]
hey @syrok94 , this has actually already been addressed.

Closed in #712

**Comment by samsul79** [comment]
Clearly 😂
