### ISSUE TITLE
Improve the search page

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/khoj#704]
Make the input box better match our other UI components (background-color, roundedness)

For results, initially make them collapsed and show just 200px in height. If the user clicks, expand and open it up for focus with the full text to display.

See https://app.khoj.dev/search

**Comment by habeebmoosa** [comment]
Hey, I want to work on this!

**Comment by sabaimran** [comment]
Go for it, @habeebmoosa ! Let me know if you need help. These are the setup instructions: https://docs.khoj.dev/contributing/development

**Comment by vr-varad** [comment]
@habeebmoosa are u still working on this issue?
