### ISSUE TITLE
Bugs? 

### ISSUE THREAD

**Issue by Gypsyaus** [khoj-ai/khoj#742]
- [ ] ![Screenshot_20240509-071808.png](https://github.com/khoj-ai/khoj/assets/170590680/85b47b4e-5c62-4cb7-baa4-891f88ae776e)

**Comment by sabaimran** [comment]
Hi @Gypsyaus , can you clarify what you did that led you here, and what are we looking at?

**Comment by Gypsyaus** [comment]
My phone was being weird n I managed to get into the system and came across the tasks and codes as a result. Was amused due to the fact the times and commands didn't match the times I was using the device.

**Comment by sabaimran** [comment]
Was this one the web view on your mobile browser? Some additional context would be helpful, I'm not super clear on what the problem is here.

**Comment by sabaimran** [comment]
Hey @Gypsyaus , I'm going to close this out as it seems like a false alarm.
