### ISSUE TITLE
[IDEA] Incorporate Google Search API

### ISSUE THREAD

**Issue by JC1738** [khoj-ai/khoj#749]
## Describe the feature you'd like
A clear and concise description of what you want to happen. Include any relevant links or screenshots or inspiration.

The project currently supports https://serper.dev/. It would be awesome for users with access to Google Cloud to be able to use the Google Search API by entering the key and search engine ID as a configuration, allowing internet searches through that mechanism.

**Comment by mdlmarkham** [comment]
What about Searxng for local installs: https://github.com/searxng/searxng
