### ISSUE TITLE
Suggestion for Persian Font Improvement

### ISSUE THREAD

**Issue by Wnb369** [khoj-ai/khoj#756]
Hello,

Your work is outstanding. I have used the web version of Khoj and I would like to suggest changing the Persian font. The current font is not very legible, and there are many issues with the letters being improperly placed next to each other in words. Thank you for all the hard work you put into this. Wishing you success.

**Comment by sabaimran** [comment]
Hi @Wnb369 ! Thanks for raising this issue. It's really important to us to make sure we're localizing appropriately. Can you confirm that your experience is similar to something in this screenshot? We might need your help in validating whether our solutions work for you. 
<img width="1075" alt="Screenshot 2024-05-26 at 20 00 58" src="https://github.com/khoj-ai/khoj/assets/65192171/eab94910-b5e6-4b21-8399-eb6c96dda05d">

**Comment by sabaimran** [comment]
Ordinarily it would be easiest if we could just use a different css class for the Persian/Arabic/Urdu fonts, but we won't be able to do that in a hard-coded way. We'll probably have to infer dynamically, with something [like this](https://laracasts.com/discuss/channels/laravel/how-to-style-font-different-if-it-is-in-arabic-language).

**Comment by Wnb369** [comment]
The problem that exists is that in some words, the letters are displayed separately from each other. As is clear in the picture you sent, there are many connected letters that are displayed separately. I will mark those and also show their correct spelling in another picture so that you can understand better.
![1](https://github.com/khoj-ai/khoj/assets/130536416/2f30c372-16eb-4c9f-9ff3-d5b5a5e1b51f)

![2](https://github.com/khoj-ai/khoj/assets/130536416/427c961c-0d3f-4567-8635-827a9fc664d1)

This issue exists only in Persian and Urdu.

**Comment by Wnb369** [comment]
Thank you for the changes you've made; it's much better than before.
