### ISSUE TITLE
[FIX] Permission denied

### ISSUE THREAD

**Issue by Eyobs-droid** [khoj-ai/khoj#761]
it says permission denied after the docker-compose up command on linux ubuntu

**Comment by sabaimran** [comment]
Can you include a stack trace, @Eyobs-droid

**Comment by Eyobs-droid** [comment]
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Dkhoj%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied

**Comment by Rounak40** [comment]
Try `sudo docker-compose up`

**Comment by Eyobs-droid** [comment]
Thank you
