### ISSUE TITLE
[FIX] Unable to logout user

### ISSUE THREAD

**Issue by Varming73** [khoj-ai/khoj#772]
I've installed khoj via the docker compose on an Ubuntu server. When I try to logout the default user (I've created a different user in the admin side) I get this error:

{"detail":"Not Found"}

## Screenshots
![image](https://github.com/khoj-ai/khoj/assets/60294362/88efc431-5a69-42c4-8e6d-a56105ad2b70)

## Platform
- Server:
    - [ ] Self-Hosted Docker
- Client:
    - [ ] Web browser
- OS:
    - [ ] Linux

### If self-hosted
- Server Version [e.g. 1.0.1]: I can't see this anywhere in the user frontend

**Comment by Varming73** [comment]
I guess the problem must be that I run as --anonymous-mode  but the documentation doesn't describe how to set it up to run in any other way. It just mentions that you have to set up Google auth but not how to do it. Any useful links or anything?

**Comment by maciekpoplawski** [comment]
I wold like to also 👍  on this issue. It would be nice to be able to use multiple users without the need for google auth. I've also created users in Django Admin but im unable to use them cause im unable to logout.

**Comment by sabaimran** [comment]
Hey folks, valid feedback. We hadn't had bunch demand for multiple users in the self-hosted instance yet, so we held off on implementing custom auth. Currently, the only two options for auth are either `anonymous-mode` (i.e., no auth) and Google auth (documentation for that is [here](https://docs.khoj.dev/miscellaneous/google_auth)). 

I hear you, there should be a way to create multiple users without having to go through all that drama. We'll prioritize some changes to make that work, but for now I'd recommend setting up the Google login if you're using the python package.

**Comment by sabaimran** [comment]
Closed with #820

**Comment by sabaimran** [comment]
Hey y'all! This is now possible, to have signed-in, authenticated users without `--anonymous-mode`. I've added the documentation here: https://docs.khoj.dev/miscellaneous/authentication.

The change will go out in the next release! Probably in a week or so.
