### ISSUE TITLE
Blackia723

### ISSUE THREAD

**Issue by Blackia723** [khoj-ai/khoj#775]
## Describe the bug
A clear and concise description of what the bug is. Please include what you were expecting to happen vs. what actually happened.

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [ ] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [x] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [ ] Linux
    - [ ] Android
    - [x] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

**Comment by sabaimran** [comment]
Hey @Blackia723 , maybe you're referring to the WhatsApp integration not working in the cloud? I pushed a fix for that a few hours ago.
