### ISSUE TITLE
[FIX]https://app.khoj.dev/ is down？, malfunction, stuck at "Generating a well-informed response"

### ISSUE THREAD

**Issue by ihorizons2022** [khoj-ai/khoj#784]
## Describe the bug
A clear and concise description of what the bug is. Please include what you were expecting to happen vs. what actually happened.

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [ ] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

**Comment by sabaimran** [comment]
Thanks for this, @ihorizons2022 , looks like we had a little trouble in some DB scaling work we were doing in the backend. Resolved now!
