### ISSUE TITLE
CSRF-Error with Docker Desktop

### ISSUE THREAD

**Issue by SchinkTasia** [khoj-ai/khoj#786]
## Describe the bug
Hi, I currently use the docker-compose.yml which is linked in the self-host documentation with the Docker Desktop Windows Software. I can´t log into the Admin panel with the http://127.0.0.1:42110 adress, because i got the "CSRF verification failed. Request aborted.". I try to add my IP to the docker-compose as environment var and disable the SSL with "KHOJ_NO_SSL="True"", and i tried "KHOJ_NO_HTTPS="True"" because in the settings.py its searching for this.

A few days ago it worked and than not anymore. i currently tried 2 different computer with the docker and non-docker installation, but each time i got the same result. When i try to connect with a custom domain from another pc i cant log in because "my credentials are wrong".

## To Reproduce
I really dont know, how to reproduce this issue.

## Screenshots
![image](https://github.com/khoj-ai/khoj/assets/35700301/25743f32-9fef-4062-a816-fffb3f27bc6c)

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [X] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [X] Web browser
    - [ ] WhatsApp
- OS:
    - [X] Windows
    - [ ] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]: Khoj v1.12.1

###  More information
I set the environment variable KHOJ_DEBUG=True in the docker-compose.yml, but i only get one line as repsonse when i try to login which says, that someone connected. So this isn´t sadly usefully for me, currently.

**Comment by debanjum** [comment]
Can you check if you can access the admin panel from localhost:42110 address instead?

**Comment by SchinkTasia** [comment]
> Can you check if you can access the admin panel from localhost:42110 address instead?

Hey,
I Guess i tried that and it doesnt changed much. I will try that again today. Just to be Sure.

**Comment by sabaimran** [comment]
Hey @SchinkTasia , do you mind sharing the `docker-compose.yml` you're using? And let me know what happens when you try accessing from http://localhost:42110. 

I made a small update here to the docker compose that would be worth trying: https://github.com/khoj-ai/khoj/commit/6d10f98498fe8ca4c4c6f086e6f9b8e9b8aad420

**Comment by SchinkTasia** [comment]
> Hey @SchinkTasia , do you mind sharing the `docker-compose.yml` you're using? And let me know what happens when you try accessing from http://localhost:42110.
> 
> I made a small update here to the docker compose that would be worth trying: [6d10f98](https://github.com/khoj-ai/khoj/commit/6d10f98498fe8ca4c4c6f086e6f9b8e9b8aad420)

Hi,
So i tried to connect via localhost. (in this example i keeped the settings like in the original docker-compose, just to check the functionality. I will definitiv change the user and secret) But i only get a "Please enter the correct username and password".
![image](https://github.com/khoj-ai/khoj/assets/35700301/e844d103-65d4-4983-be00-c922e977dab9)

When i connect over 192.168.1.4 i got the following:
![image](https://github.com/khoj-ai/khoj/assets/35700301/16dbba36-c817-4deb-afcc-fbf70145c33b)

Following my docker-compose.yml (like i said, when i can login, i will change the login data. but even when i change it, it will be no difference at the moment.)
`version: "3.9"
services:
  database:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - khoj_db:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  server:
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "42110:42110"
    working_dir: /app
    volumes:
      - khoj_config:/root/.khoj/
      - khoj_models:/root/.cache/torch/sentence_transformers
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - KHOJ_NO_HTTPS="True"
      - KHOJ_DOMAIN=192.168.1.4
      - KHOJ_DJANGO_SECRET_KEY=secret
      - KHOJ_DEBUG=True
      - KHOJ_ADMIN_EMAIL=username@example.com
      - KHOJ_ADMIN_PASSWORD=Password
    command: --host="0.0.0.0" --port=42110 -vv --anonymous-mode


volumes:
  khoj_config:
  khoj_db:
  khoj_models:`

When you need something else, just tell me.

**Comment by SchinkTasia** [comment]
**Update**
I tried the docker container on a different laptop with an OpenSuse Tumbleweed OS.
On this plattform everythings works fine, but sadly i cant use it, because the CPU and GPU are not powerfull enough.
And i cant change the OS of my current Windows 10 Computer.

**Comment by IMJONEZZ** [comment]
I am also getting CSRF verification failures on Firefox on Ubuntu. Would love a fix

**Comment by IMJONEZZ** [comment]
I’m  not sure which I’m hitting, because the error is a 403 connection, but
the stack trace says CSRF verification error. For me it happens regardless
of browser or port, I’ve confirmed it doesn’t work on chrome or port 42110
either.


Dňa št 13. 6. 2024 o 8:04 Debanjum ***@***.***> napísala(a):

**Comment by mingLvft** [comment]
mee to

**Comment by satisl** [comment]
same csrf error

**Comment by debanjum** [comment]
Hi folks, I was able to verify that the latest Khoj run on Windows (11) + WSL2 + Docker (with WSL2 backend) does not hit the CSRF issue when accessing the admin panel at `http://localhost:42110/server/admin` or `http://<i.p>:42110/server/admin`. 

When trying to access Khoj admin panel over an i.p or domain you need to ensure the environment variable `KHOJ_DOMAIN=<your_i.p>` in your `docker-compose.yml` is (correctly) set and uncommented. See the new [Remote Access Doc](http://localhost:3000/advanced/remote) and the updated [Self Hosting Setup Docs](http://localhost:3000/get-started/setup?os=windows&server=docker)

Let us know if you're still hitting the issue, where/how you're running Khoj and client or server console logs to help debug this!
