### ISSUE TITLE
[FIX] firefox CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by thistleknot** [khoj-ai/khoj#794]
## Describe the bug
A clear and concise description of what the bug is. Please include what you were expecting to happen vs. what actually happened.
Trying to login to admin on 127

## To Reproduce
Trying to login to admin on 127

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [X] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [X] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

**Comment by debanjum** [comment]
Hi @thistleknot, could you check if you're able to use localhost:42110 to login to Khoj admin panel instead of 127.0.0.1:42110?

**Comment by debanjum** [comment]
Awesome! Closing this issue. Verified [the docs](https://docs.khoj.dev/get-started/setup#2-configure) mention accessing the admin panel via localhost:42110 as well.
