### ISSUE TITLE
[FIX]macbook m2 Ollama / Khoj error

### ISSUE THREAD

**Issue by moffefei** [khoj-ai/khoj#813]
## docker khoj-server log↓

[khoj ollama server error log.md](https://github.com/user-attachments/files/15797887/khoj.ollama.server.error.log.md)

## To Reproduce
follow the steps : [https://docs.khoj.dev/miscellaneous/ollama/](url)

## Screenshots
<img width="1512" alt="image" src="https://github.com/khoj-ai/khoj/assets/132885305/77004e7f-ef29-42f8-b974-fd8dfb463900">

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [✅ ] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [✅ ] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version :1.13.0

**Comment by sabaimran** [comment]
Hey @moffefei , can you share your ollama chat config with me?

**Comment by moffefei** [comment]
> Hey @moffefei , can you share a screenshot of your ollama chat config with me?
here the ollama chat config:
<img width="1032" alt="image" src="https://github.com/khoj-ai/khoj/assets/132885305/bd8dd8b6-7ec5-4acc-a89a-22a39a1a514e">
<img width="1064" alt="image" src="https://github.com/khoj-ai/khoj/assets/132885305/84575cbd-4b24-4252-b8ff-f0fad2437f7f">

**Comment by moffefei** [comment]
> Hey @moffefei , can you share a screenshot of your ollama chat config with me?

upgraded docker & ollama already.

**Comment by sabaimran** [comment]
No, I mean inside khoj. I'd like to see the open ai processor conversation settings in the admin page.

**Comment by moffefei** [comment]
> No, I mean inside khoj. I'd like to see the open ai processor conversation settings in the admin page.不，我是说在 khoj 里面。我想在管理页面中查看打开的人工智能处理器对话设置。

sorry,but this page?

**Comment by moffefei** [comment]
> No, I mean inside khoj. I'd like to see the open ai processor conversation settings in the admin page.不，我是说在 khoj 里面。我想在管理页面中查看打开的人工智能处理器对话设置。
sorry,but this page? ![Uploading 截屏2024-06-12 12.11.06.png…]()

**Comment by moffefei** [comment]
> No, I mean inside khoj. I'd like to see the open ai processor conversation settings in the admin page.不，我是说在 khoj 里面。我想在管理页面中查看打开的人工智能处理器对话设置。
sorry, but this page?
<img width="1459" alt="截屏2024-06-12 12 11 06" src="https://github.com/khoj-ai/khoj/assets/132885305/9842490a-9f59-404c-8753-10e1140d6eb2">

**Comment by moffefei** [comment]
try much but not fixed

**Comment by sabaimran** [comment]
No, I mean in the admin panel, which should be here: http://localhost:42110/server/admin/database/openaiprocessorconversationconfig/
<img width="812" alt="Screenshot 2024-06-12 at 16 46 47" src="https://github.com/khoj-ai/khoj/assets/65192171/3a2538f1-b7bc-493f-b872-ea05de47cc3f">

Make sure the URL you're using is `http://localhost:11434/v1/`. The `/v1` is important.

**Comment by mominfaruk** [comment]
Same issue is happening for macbook m1

**Comment by adityanemali** [comment]
Upgrading ollama worked for me.

curl -fsSL https://ollama.com/install.sh | sh
