### ISSUE TITLE
[FIX] obsedian picture won't render on notes after installing khoj. after remove picture renders again

### ISSUE THREAD

**Issue by NanHeSam** [khoj-ai/khoj#816]
## Describe the bug
A clear and concise description of what the bug is. Please include what you were expecting to happen vs. what actually happened.
picture won't render on notes after installing khoj. after remove picture renders again
## Screenshots
when Khoj is enabled
<img width="554" alt="image" src="https://github.com/khoj-ai/khoj/assets/15306889/831e721c-7c01-41a9-999f-e2064dc359d4">
<img width="805" alt="image" src="https://github.com/khoj-ai/khoj/assets/15306889/70063370-de33-4d8c-bc2e-f65163a6883c">
when Khoj is disabled and restart obsedian
<img width="810" alt="image" src="https://github.com/khoj-ai/khoj/assets/15306889/f702a11c-b731-4ba4-a486-d4e22b53324a">
<img width="883" alt="image" src="https://github.com/khoj-ai/khoj/assets/15306889/4974679f-3f9f-473b-af67-94cfd63e30f0">

## Platform
- Server:
    - [x] Cloud-Hosted (https://app.khoj.dev)
    - [ ] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [x] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [x] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

**Comment by sabaimran** [comment]
Just to clarify, these are your normal notes, not something you've pasted into the Khoj panel, right?

**Comment by NanHeSam** [comment]
> Just to clarify, these are your normal notes, not something you've pasted into the Khoj panel, right?

Yes, it's the normal notes that i added before install Khoj

**Comment by debanjum** [comment]
Hey @NanHeSam, thanks for reporting the issue! Is the image local on your file system or an external link (e.g starts with `http`)?

**Comment by NanHeSam** [comment]
these pictures are all local file. but i just tried to embeded a image on the internet and it also has this behavior (showing normally when disabled Khoj but break when enable Khoj) 
`![[Pasted image 20240612182753.png]]`
`![Engelbart](https://history-computer.com/ModernComputer/Basis/images/Engelbart.jpg)`

these are the format that i'm using

**Comment by NanHeSam** [comment]
awesome, thank you  so much for the quick fix. I will verify that once it's release

**Comment by debanjum** [comment]
Hey @NanHeSam, this issue was resolved in 08c3aa496d262f6cd6df56d675e595de999000e8. 
Let me know if you're still facing problems loading the image?

**Comment by NanHeSam** [comment]
Yes, I have just test and confirmed it's resolved. Thank you!
