### ISSUE TITLE
Fix Post Login Redirects for Khoj Pages behind Auth #578

### ISSUE THREAD

**Issue by mingLvft** [khoj-ai/khoj#818]
Redirect to a specific authenticated page after logging in doesn't currently work. Always directed to post-login landing page, even when redirect link in URL

**Comment by debanjum** [comment]
Can you share an example URL with that behavior? It does redirect to at least some authenticated pages I tested (e.g https://app.khoj.dev/login?next=http%3A%2F%2Fapp.khoj.dev%2Fautomations)

**Comment by sabaimran** [comment]
hey @mingLvft , I'll close this for now since we haven't had an update, but please comment here in case you're still seeing that behavior and we can investigate. It's possible some pages aren't properly creating their redirect URIs.
