### ISSUE TITLE
[FIX] Pre-built Docker Container Missing Production Dependencies and Outdated

### ISSUE THREAD

**Issue by asheliahut** [khoj-ai/khoj#833]
## Describe the bug
The pre-built Docker container available on GitHub packages does not include the production dependencies for 'resend' and others. Additionally, the production tagged container is 7 months old and is not being updated. When attempting to build from a remote location on Portainer, access to the production features is required without maintaining a custom container image.

## To Reproduce
1. Pull the pre-built Docker container from GitHub packages.
2. Attempt to use features that require production dependencies such as 'resend'.
3. Notice that the dependencies are missing and the production features are unavailable.

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [X] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [X] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [X] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version: latest at the time it is 1.14.0

## Additional context
I am trying to build from a location without the code next to it on Portainer and want access to the production features without having to maintain my own container image. Regular updates to the production tagged container would also be beneficial.

**Comment by debanjum** [comment]
Hey @asheliahut, fair ask. Let me make the prod images public. Don't remember why it was made private in the first place

**Comment by debanjum** [comment]
Hey @asheliahut, the [Khoj cloud docker image](https://github.com/khoj-ai/khoj/pkgs/container/khoj-cloud) has been made public. So you should be able to use Khoj with production dependencies and the latest changes (including the new UI) without having to maintain your own container images.

Apologize for the delay. Let me know if you hit any issues using these khoj-cloud container images
