### ISSUE TITLE
Consider outline hierarchy when searching?

### ISSUE THREAD

**Issue by yantar92** [khoj-ai/khoj#85]
I am playing around with the search and comparing the results with my https://github.com/yantar92/org-ql/ setup.

One obvious point that is not handled by khoj is matching the outline path for nodes:
Consider the following outline structure:

* Topics
** Emacs
*** debanjum [Github] debanjum/khoj: Natural Language Search Engine for your Org-Mode and Markdown notes, Beancount transactions and Photos

A natural way to search for the deepest node is "emacs org search engine", but khoj does not yield the match here.

**Comment by debanjum** [comment]
Fair suggestion to improve results. It's in my mental backlog of improvements. Good that it's been explicitly added as an issue to track :)

Adding outline data (e.g heading, tags) to a node seems like a good idea to improve search quality. Most org search tools like default org-mode search, `org-rifle` (and your fork of `org-ql` it seems?) already do this. 

An entries parent data isn't provided by OrgNode currently. But once I've included that data, adding this should be give a easy, quick win for improving search results.
