### ISSUE TITLE
ERROR: Cannot install khoj because these package versions have conflicting dependencies[FIX]

### ISSUE THREAD

**Issue by diweiqiang** [khoj-ai/khoj#873]
## Describe the bug
when i install  khoj in my mac with Intel Machines, run "python -m pip install khoj" and i got the following error:
ERROR: Cannot install khoj because these package versions have conflicting dependencies.

**Comment by debanjum** [comment]
Hey @diweiqiang, can you share more details of the error message you saw? A screenshot or the complete error log when installing khoj would be helpful to debug the issue

**Comment by diweiqiang** [comment]
![image](https://github.com/user-attachments/assets/d1d90128-7c4a-4a64-9d23-70f2af132121)
错误提示如上

**Comment by shantanuSakpal** [comment]
hey @diweiqiang  did you start the virtural environment before installing the libraries?
```bash
# Get Khoj Code
git clone https://github.com/khoj-ai/khoj && cd khoj

# Create, Activate Virtual Environment
python3 -m venv .venv && source .venv/bin/activate

# For MacOS or zsh users run this
pip install -e '.[dev]'
```

**Comment by diweiqiang** [comment]
I enabled the conda virtual environment, but did not execute the command “pip install -e '.[dev]',” which may be the cause of the problem. Thank you very much for pointing out the correct way to execute it.

**Comment by shantanuSakpal** [comment]
Great. You can see further installation details at https://docs.khoj.dev/contributing/development/

**Comment by sabaimran** [comment]
Thanks for supplying the fix @shantanuSakpal . @diweiqiang , it would also be helpful to know which command you originally used for install.
