### ISSUE TITLE
Pre-loaded configurations

### ISSUE THREAD

**Issue by sm18lr88** [khoj-ai/khoj#882]
The setup for the locally hosted Docker version is still complicated (it used to be way simpler in the earlier version of Khoj), and the instructions are not very clear on how to load various models, embedding engines, etc.

Consider offering pre-loaded choices for LLMs and Embedding choices from a drop-down menu.

For example, a drop-down menu in the chat models where users can simply select the LLM provider, model, and input their API key.
For embeddings likewise: a list of all the various models users can use, from a simple drop-down menu rather than having to type it in.

I keep trying this app here and there but I only ever managed to get the initial version to ever work.

Thanks.

**Comment by debanjum** [comment]
Hey @sm18lr88, thanks for opening this issue and pointing out a good area for improvement! I made some changes to address this:
1. Khoj now sets up a decent set of default chat models on first run. 
   Folks using Docker to setup Khoj can set their provider specific API keys in the [docker-compose.yml](https://github.com/khoj-ai/khoj/blob/master/docker-compose.yml) before first run to enable provider specific default chat models. See the updated [Self Hosting Docs](http://localhost:3000/get-started/setup?server=docker) for details
3. I've also simplified the Docker setup in #919, so configuring Khoj via the admin panel isn't necessary to get started with using self hosted Khoj.

We should add a decent set of default embedding models as well for folks to get started (e.g include a decent default multi-lingual embedding model). This can be done as a follow-up.

Do try out the newer Khoj docker setup. Hopefully it goes better this time 🤞🏽

**Comment by h4rsh-k** [comment]
> not sure if it is easier now but when I try to run the docker-compose.yml I receive an unauthorized error:
> 
> > [+] Running 3/3
> > ✘ sandbox Error  Head "https://ghcr.io/v2/khoj-ai/terrarium/manifests/latest": unauthorized                                                                                                                                            0.4s  ✘ server Error   context canceled                                                                                                                                                                                                      0.4s  ✘ database Error context canceled                                                                                                                                                                                                      0.4s Error response from daemon: Head "https://ghcr.io/v2/khoj-ai/terrarium/manifests/latest": unauthorized

+1 Getting the same errors

**Comment by debanjum** [comment]
Woops, thanks for the notice! Just made the newly released [code sandbox](https://github.com/khoj-ai/terrarium) docker image at ghcr.io/khoj-ai/terrarium public. So `docker-compose up` should work now.

Background:
The [newly released](https://github.com/khoj-ai/khoj/releases/1.28.0) code tool allows Khoj to do data analysis and create charts for you by running python code in a sandbox using cohere's terrarium+pyodide. This tool is still experimental, so feel free to share any feedback on setup or usage.
