### ISSUE TITLE
[FIX] Allow Setting File Types to Sync from Obsidian

### ISSUE THREAD

**Issue by Haqbani** [khoj-ai/khoj#893]
## Describe the bug
i get this eveytime i click update or restart "Failed to sync your content with Khoj server.Requests were throttled. Upgrade your subscription or try again "

## Screenshots
![Xnapper-2024-08-20-23 41 30](https://github.com/user-attachments/assets/08dbd31f-32e9-41cb-a521-69fd143c04f8)

## Platform
- Server:
    - [x] Cloud-Hosted (https://app.khoj.dev)
    - [ ] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [x] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [x] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

**Comment by sabaimran** [comment]
Hey @Haqbani , do you mind shooting me an email to tell me what email address is associated with your Khoj cloud account? We do have a limit configured for a given packet of data to be limited to 75mb for unsubscribed users and 100mb for subscribed users. Is it possible that your Obsidian knowledge base is larger than that?

**Comment by Haqbani** [comment]
Hello Dear,

Thanks for getting back to me. my email in Khoj is ***@***.***

best,

**Comment by Haqbani** [comment]
are there any feedback on this ?

**Comment by sabaimran** [comment]
Can you send me an email from your account to team at khoj.dev? It gets censored out in the GitHub issue.

**Comment by Haqbani** [comment]
> Can you send me an email from your account to team at khoj.dev? It gets censored out in the GitHub issue.

hi, i have sent it.

**Comment by huachuman** [comment]
is there a way to only upload notes and not the entire vault?

**Comment by Haqbani** [comment]
> is there a way to only upload notes and not the entire vault? a single piece of media or audio file could send someone over the limit.

I certainly hope so. From what I understand, there is no option to exclude file types. Although I don't have any media, I do have over 300 notes, and I think I have exceeded the limit. Unfortunately, this isn't worth the $30 monthly price. I'm currently waiting for their feedback.

**Comment by sabaimran** [comment]
@huachuman are you also using obsidian? We're going to add in a filter to the plugin that allows you to exclude media files. Others have reported this issue as well. 

@Haqbani sorry for the delay! Just responded back to you via email. Let's see if we can increase the rate limits to support your data size.

**Comment by huachuman** [comment]
@sabaimran yes I'm using Obsidian. Now I understand why it never worked.
