### ISSUE TITLE
[FIX] sometimes llm_thread throw exception because pool connect to openai api server

### ISSUE THREAD

**Issue by thinker007** [khoj-ai/khoj#894]
## Describe the bug
A clear and concise description of what the bug is. Please include what you were expecting to happen vs. what actually happened.

## To Reproduce
first httpx throw exception because pool connection to openai api server
then client.chat.completions.create throw exception 
chat = client.chat.completions.create(
        stream=True,
        messages=formatted_messages,
        model=model_name,  # type: ignore
        temperature=temperature,
        timeout=20,
        **(model_kwargs or dict()),
    )
finally: llm_thread not exit 
and causing  the generator is  not closed .

So the whole khoj server  hangs

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [ ] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

**Comment by debanjum** [comment]
Just fixed the offline chat stream not being closed properly issue yesterday in https://github.com/khoj-ai/khoj/commit/5927ca803277901590466ac3deb621f5a0e67210. 

Let me know if you're still seeing it in release >=1.21.3

**Comment by thinker007** [comment]
> Just fixed the offline chat stream not being closed properly issue yesterday in [5927ca8](https://github.com/khoj-ai/khoj/commit/5927ca803277901590466ac3deb621f5a0e67210).
> 
> Let me know if you're still seeing it in release >=1.21.3

the same bug exists in https://github.com/khoj-ai/khoj/blob/master/src/khoj/processor/conversation/openai/utils.py

when throw exceptions whole application hangs

**Comment by debanjum** [comment]
Ah, didn't catch that. Thanks for pointing it out. Let me fix that up in a bit
