### ISSUE TITLE
[FIX] cannot set RESEND_API_KEY on the docker version

### ISSUE THREAD

**Issue by lethanhviet** [khoj-ai/khoj#905]
## Describe the bug

Setting the RESEND_API_KEY on the docker environment return an error.

Traceback (most recent call last):
  File "/app/src/khoj/main.py", line 93, in <module>
    from khoj.configure import configure_routes, initialize_server, configure_middleware
  File "/app/src/khoj/configure.py", line 44, in <module>
    from khoj.routers.api_content import configure_content, configure_search
  File "/app/src/khoj/routers/api_content.py", line 37, in <module>
    from khoj.routers.helpers import (
  File "/app/src/khoj/routers/helpers.py", line 90, in <module>
    from khoj.routers.email import is_resend_enabled, send_task_email
  File "/app/src/khoj/routers/email.py", line 28, in <module>
    resend.api_key = RESEND_API_KEY
NameError: name 'resend' is not defined

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [x] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

**Comment by sabaimran** [comment]
hi @lethanhviet , sorry about this. this is because our prod docker image for khoj-cloud isn't made public. we'll go ahead and make that public, and then you'll have to use that.

**Comment by nexty5870** [comment]
Hello - I have the same, although I have setup the RESEND_API_KEY in my docker-compose file I have the same error

`File "/app/src/khoj/routers/email.py", line 28, in
resend.api_key = RESEND_API_KEY
NameError: name 'resend' is not defined`

**Comment by debanjum** [comment]
Hey @nexty5870 can you use the `khoj-cloud:latest` docker image? This should allow you to enable magic links based auth in your self-hosted Khoj with resend
