### ISSUE TITLE
Trying to Self-Host on Ubuntu (using pip) - Can't Complete Install

### ISSUE THREAD

**Issue by mdlmarkham** [khoj-ai/khoj#910]
I'm trying to self-host Khoj on a Ubuntu 22.04.05 environment running in a ProxMox LCX. This is a clean install of Ubuntu. I followed the Install Method 2, and get the very helpful message "Killed" directly after Collecting torch==2.2.2 as shown in the screenshot below:

## Screenshots
![image](https://github.com/user-attachments/assets/59408c88-ba8e-4a52-aeb4-75655f56092c)

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [ ] Self-Hosted Docker
    - [X] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

**Comment by debanjum** [comment]
The "Killed" message is usually seen when the app/os runs out of available memory/RAM. How much RAM/memory does your Ubuntu machine have?

**Comment by debanjum** [comment]
Closing this issue because of lack of actionable information
