### ISSUE TITLE
Trying to self host on Ubuntu using Docker - /server/admin returns bad request (400)

### ISSUE THREAD

**Issue by mdlmarkham** [khoj-ai/khoj#911]
![image](https://github.com/user-attachments/assets/e643f652-7aa8-42af-94e3-26bb879a3532)

**Comment by stevennt** [comment]
Same problem. It worked before.

**Comment by debanjum** [comment]
Hey @mdlmarkham , @stevennt. I've simplified the Docker setup in #919. I was able to remotely access the Admin Panel on the self-hosted Khoj setup via Docker. The `KHOJ_DOMAIN` environment variable just needs to be set correctly.

See the updated [Self Hosting Docs](https://docs.khoj.dev/get-started/setup?os=windows&server=docker) and added new documentation for [Remote Access Doc](https://docs.khoj.dev/advanced/remote) for details.

I'm marking this issue as resolved for now. But feel free to re-open it and share where you get stuck if you aren't able to use self hosted Khoj over the network?
