### ISSUE TITLE
[FIX] The "Create Agent" button doesn't trigger anything

### ISSUE THREAD

**Issue by vibl** [khoj-ai/khoj#915]
## Describe the bug
The "Create Agent" button doesn't trigger anything (apart from a GET request to /sessions, according to DevTools).

No error in the console. 

## To Reproduce
Click on the button.

## Platform
- Server:
    - [X] Cloud-Hosted (https://app.khoj.dev)
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [X] Web browser: Chrome latest
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [X] Linux
    - [ ] Android
    - [ ] iOS

**Comment by sabaimran** [comment]
Hey @vibl , There's actually supposed to be a `coming soon` notification that comes up there, but it's really finnicky. This feature is in progress atm. Feel free to share any info you wnat about what you're looking for here or what you'd want. 

![Screenshot 2024-09-16 at 13 51 21](https://github.com/user-attachments/assets/dc9a5cd6-42e9-4aa8-a1fb-5ea6a9540b0f)

**Comment by shantanuSakpal** [comment]
yeah, its not working for me either, on ubuntu 24, brave, looking into it, should be something minor
