### ISSUE TITLE
How to define non -standard postgresql port?

### ISSUE THREAD

**Issue by andreiramani** [khoj-ai/khoj#922]
## Describe the bug

I have non-standard postgresql port, how do we config custom port for khoj?

--- error in python terminal ---
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
        Is the server running on that host and accepting TCP/IP connections?
---

## Platform
- Server:
    - [ ] Self-Hosted Python package

- Client:
    - [ ] Web browser

- OS:
    - [ ] Windows 11, RTX 3050

**Comment by debanjum** [comment]
You'd need to set the `POSTGRES_PORT` environment variable to the port your Postgres DB is available on. You can also set `POSTGRES_HOST` if it's at a non-standard url. 

See the Khoj `docker-compose.yml` to find configurable environment variables for reference
