### ISSUE TITLE
[FIX] 'Configure' giving 404 response on https://khoj.dev/

### ISSUE THREAD

**Issue by negativenagesh** [khoj-ai/khoj#927]
# 404 Error response on https://khoj.dev/

### Current Behavior:
When I go to https://khoj.dev/ and scroll down to 'Your Research Copilot' section and 'Any Model' as I mentioned below and click on 'configure' it gives 404 response --> (https://app.khoj.dev/config), Can anyone explain why its giving an error response, or what it was supposed give?

### Element where this is occurring:
```html
<div class="framer-m8e2nr-container" style="opacity: 1; transform: perspective(1200px); transform-origin: 50% 50% 0px;">

    <a class="framer-rxHwW framer-qijx81 framer-v-qijx81 framer-1o383ss" data-framer-name="Variant 1" href="https://app.khoj.dev/config" rel="noopener" style="background-color: var(--token-a378a457-09c9-4e21-8971-31a4dc6ae8ea, rgb(17, 16, 17)); border-radius: 24px; transform: none; transform-origin: 50% 50% 0px;">
         <div class="framer-1dzv1qw" data-framer-component-type="RichTextContainer" style="outline: none; display: flex; flex-direction: column; justify-content: flex-start; flex-shrink: 0; --extracted-r6o4lv: rgb(255, 255, 255); --framer-paragraph-spacing: 16px; transform: none; transform-origin: 50% 50% 0px;">
                <p class="framer-text" style="--font-selector: RlM7U2F0b3NoaS1tZWRpdW0=; --framer-font-family: &quot;Satoshi&quot;, &quot;Satoshi Placeholder&quot;, sans-serif; --framer-font-weight: 500; --framer-line-height: 24px; --framer-text-color: var(--extracted-r6o4lv, rgb(255, 255, 255));">Configure</p>
          </div>
     </a>
</div>
```
  ```javascript
{"detail":"Not Found"}
```
![image](https://github.com/user-attachments/assets/224f39ba-ebc7-4417-8fd1-db72b77117bc)

### Reproduce
1. Open https://khoj.dev/
2. scroll down to reach --> 'Your Research Copilot' section, See image below
3. Click on 'Configure'
4. Gives response
  ```javascript
{"detail":"Not Found"}
```

### Screenshots of the error:
![image](https://github.com/user-attachments/assets/00af417f-61c3-44dc-9f08-3906edac4f48)
![image](https://github.com/user-attachments/assets/13a01f6f-fa75-4bdd-942c-52b5b61e73ac)

## Platform
- Server:
    - [ ] Cloud-Hosted (https://khoj.dev/)

- Client:
    - [ ] Web browser

- OS:
    - [ ] Windows

**Comment by sabaimran** [comment]
Thanks for reporting! This should be fixed now.

**Comment by negativenagesh** [comment]
> Thanks for reporting! This should be fixed now.

@sabaimran Thank you...
## Its working completely fine now..
I wonder no one noticed this, I spotted this like a week ago, and I studied a bit about @khoj-ai and wrote an issue today..

![image](https://github.com/user-attachments/assets/0408d020-5624-42df-83d2-a44e6277870a)
