### ISSUE TITLE
[IDEA] Make the API-s available to build custom interfaces: List of API-s

### ISSUE THREAD

**Issue by stevennt** [khoj-ai/khoj#932]
It would be great if Khoj exposes the List of API-s so users can build custom flows / UI-s. That includes custom font-end, custom document upload & grouping, etc.

Thanks.

**Comment by sabaimran** [comment]
Hey @stevennt ! You can see the API docs here: https://app.khoj.dev/redoc.

You'll need to use the user token from your settings page when you're making protected queries with an `Authorization: Bearer` header. If you do end up sharing something, please send it my way! Would love to check it out.

**Comment by debanjum** [comment]
Closing this issue as Khoj APIs are already available for reference
