### ISSUE TITLE
[FIX] Multibyte query support

### ISSUE THREAD

**Issue by adamist521** [khoj-ai/khoj#935]
## Describe the bug
I get following error when I input multibyte character when querying.

```
error in process sentinel: Multibyte text in HTTP request: POST /api/chat?client=emacs HTTP/1.1
MIME-Version: 1.0
Connection: keep-alive
Host: 127.0.0.1:42110
Accept-encoding: gzip
Accept: */*
User-Agent: URL/Emacs Emacs/29.1 (Mac; aarch64-apple-darwin23.4.0)
Authorization: Bearer YOUR_KHOJ_CLOUD_API_KEY
Content-Type: application/json
Content-length: 23

{"q":"日本語いけますか?","n":8}
```

## To Reproduce
- Input Multibyte Char(in my case Japanese) to Chat (Query) to Khoj

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [X] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [X] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [X] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]: v1.24.1 

## Additional context
Searching around, I've found some issues seems to relate to this bug so I'll list it below.
- https://github.com/karthink/gptel/issues/4
- https://github.com/rksm/org-ai/issues/3
- https://github.com/karthink/gptel/issues/2

**Comment by debanjum** [comment]
Thanks for the related bug references and a clear, reproducible bug report. This should be fixed now (encoded query param and api-token header as utf-8). 

Do let me know if you're still hitting the issue though?
