### ISSUE TITLE
[FIX] Gemini models return FINISH_REASON_UNSPECIFIED

### ISSUE THREAD

**Issue by rehandaphedar** [khoj-ai/khoj#939]
## Describe the bug
Gemini chat models return the following string for all prompts:
```
I can’t talk further about that because of FINISH_REASON_UNSPECIFIED issue.
```

## To Reproduce
- Follow the steps [in the docs](https://docs.khoj.dev/get-started/setup/?os=linux) for Linux + Docker.
- In docker-compose.yaml, set `GEMINI_API_KEY`, `KHOJ_NO_HTTPS=true`, and `KHOJ_DOMAIN=localhost`.
- Run the docker image, wait till the server is ready, then go to http://localhost:42110.
- Send any message (eg. "Hi") in the homepage prompt.

## Screenshots
![image](https://github.com/user-attachments/assets/ed38c8b0-8b01-4ffd-bbe7-c6739ff48285)

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [X] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [X] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [X] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]: `1.25.0`

## Additional context

The logs state this:
```
server-1    | [12:46:05.520678] WARNING  khoj.processor.conversation.google.utils utils.py:131
server-1    |                            : LLM Response Prevented for                         
server-1    |                            gemini-1.5-flash:                                    
server-1    |                            I can't talk further about that because              
server-1    |                            of **FINISH_REASON_UNSPECIFIED issue.**.             
server-1    |                            Last Message by user: Query: Hi                      
```

I've been trying to get more information about the issue by editing `utils.py` in the running docker image to print relevant variables, like:

- `chat_session`, `formatted_messages` after line 123
- `candidates`, `prompt_feedback` after line 154

But, it doesn't seem to work.

I also noticed that the first message sent will 404 a request to `/index.txt`, while subsequent messages will 404 to `/[message]`:
![image](https://github.com/user-attachments/assets/1de3f7d6-3794-4d13-9b00-b91d8eabb0f3)
![image](https://github.com/user-attachments/assets/922a1ac3-70d5-4a35-bf08-6f4ee741a8ae)

**Comment by sabaimran** [comment]
Hey @rehandaphedar , I just pushed a fix for this. Gemini made a small change in how they send response chunks. It'll be in the next release, which will hopefully be today. See relevant commit: https://github.com/khoj-ai/khoj/commit/07ab8ab9313bf6bc9be993658c81eb77a6ed53b2

**Comment by debanjum** [comment]
Hey @rehandaphedar , thanks for the detailed bug report and investigation!
- The failing calls to `index.txt` aren't actual issues with Khoj (Next.js tries to do some pre-fetch for performance). Not sure why there were calls to `/[message]`. Actual chat message calls should just go to `/api/chat`.
- I've just triggered a new release with @sabaimran's fix for the issue. So if you pull the latest docker image in an hour, you should be able to chat with Gemini models (tip: try the new `gemini-1.5-flash-002`, it feels much better IMO)

I'll mark this issue as resolved, but feel free to re-open it if you're still seeing this error

**Comment by rehandaphedar** [comment]
Thanks! Will try soon.

**Comment by sabaimran** [comment]
Also, just saw this comment that you left -

> I've been trying to get more information about the issue by editing utils.py in the running docker image to print relevant variables, like... But it doesn't seem to work.

If you're running the self-hosted setup with Docker, you'll need to rebuild the container when you make changes. To do that, you run `docker-compose build --no-cache`. 

Let me know if you're still facing that issue?

**Comment by rehandaphedar** [comment]
Noted, it's fixed for me after I pulled the new image.
