### ISSUE TITLE
Can't work on self-host.

### ISSUE THREAD

**Issue by YIRU69** [khoj-ai/khoj#959]
On my windows11 system.

I use the model llama3.1:8b. Error messages are as follows.

## Screenshots
![image](https://github.com/user-attachments/assets/92220f30-c5c9-4202-8c43-14a664320238)

## Platform
- Server:
    - [x] Self-Hosted source code
- OS:
    - [x] Windows

### If self-hosted
- Server Version [e.g. 1.0.1]: 1.28.3

**Comment by YIRU69** [comment]
[19:38:25.054388] INFO     khoj.routers.helpers: Loading Offline Chat Model...                                   helpers.py:149
                  ERROR    khoj.utils.config: Error while loading offline chat model: not enough values to unpack  config.py:80
                           (expected 2, got 1)
                           ╭───────────────────────── Traceback (most recent call last) ─────────────────────────╮ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\khoj\utils\config.py:77 in __init__              │ 
                           │                                                                                     │ 
                           │   74 │   │   self.chat_model = chat_model                                           │ 
                           │   75 │   │   self.loaded_model = None                                               │ 
                           │   76 │   │   try:                                                                   │ 
                           │ ❱ 77 │   │   │   self.loaded_model = download_model(self.chat_model, max_tokens=max │ 
                           │   78 │   │   except ValueError as e:                                                │ 
                           │   79 │   │   │   self.loaded_model = None                                           │ 
                           │   80 │   │   │   logger.error(f"Error while loading offline chat model: {e}", exc_i │ 
                           │                                                                                     │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\khoj\processor\conversation\offline\utils.py:31  │ 
                           │ in download_model                                                                   │ 
                           │                                                                                     │ 
                           │   28 │   │   kwargs["chat_format"] = "gemma"                                        │ 
                           │   29 │                                                                              │ 
                           │   30 │   # Check if the model is already downloaded                                 │ 
                           │ ❱ 31 │   model_path = load_model_from_cache(repo_id, filename)                      │ 
                           │   32 │   chat_model = None                                                          │ 
                           │   33 │   try:                                                                       │ 
                           │   34 │   │   chat_model = load_model(model_path, repo_id, filename, kwargs)         │ 
                           │                                                                                     │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\khoj\processor\conversation\offline\utils.py:63  │ 
                           │ in load_model_from_cache                                                            │ 
                           │                                                                                     │ 
                           │   60                                                                                │ 
                           │   61 def load_model_from_cache(repo_id: str, filename: str, repo_type="models"):    │ 
                           │   62 │   # Construct the path to the model file in the cache directory              │ 
                           │ ❱ 63 │   repo_org, repo_name = repo_id.split("/")                                   │ 
                           │   64 │   object_id = "--".join([repo_type, repo_org, repo_name])                    │ 
                           │   65 │   model_path = os.path.sep.join([HF_HUB_CACHE, object_id, "snapshots", "**", │ 
                           │      filename])                                                                     │ 
                           │   66                                                                                │ 
                           ╰─────────────────────────────────────────────────────────────────────────────────────╯ 
                           ValueError: not enough values to unpack (expected 2, got 1)
[19:38:25.070403] ERROR    uvicorn.error: Exception in ASGI application                                         h11_impl.py:411

                           ╭─────────────────────── Traceback (most recent call last) ────────────────────────╮ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\uvicorn\protocols\http\h11_impl.py:406 in     │ 
                           │ run_asgi                                                                         │ 
                           │                                                                                  │ 
                           │   403 │   # ASGI exception wrapper                                               │ 
                           │   404 │   async def run_asgi(self, app: ASGI3Application) -> None:               │ 
                           │   405 │   │   try:                                                               │ 
                           │ ❱ 406 │   │   │   result = await app(  # type: ignore[func-returns-value]        │ 
                           │   407 │   │   │   │   self.scope, self.receive, self.send                        │ 
                           │   408 │   │   │   )                                                              │ 
                           │   409 │   │   except BaseException as exc:                                       │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\uvicorn\middleware\proxy_headers.py:70 in     │ 
                           │ __call__                                                                         │ 
                           │                                                                                  │ 
                           │   67 │   │   │   │   │   port = 0                                                │ 
                           │   68 │   │   │   │   │   scope["client"] = (host, port)  # type: ignore[arg-type │ 
                           │   69 │   │                                                                       │ 
                           │ ❱ 70 │   │   return await self.app(scope, receive, send)                         │ 
                           │   71                                                                             │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\fastapi\applications.py:1054 in __call__      │ 
                           │                                                                                  │ 
                           │   1051 │   async def __call__(self, scope: Scope, receive: Receive, send: Send)  │ 
                           │   1052 │   │   if self.root_path:                                                │ 
                           │   1053 │   │   │   scope["root_path"] = self.root_path                           │ 
                           │ ❱ 1054 │   │   await super().__call__(scope, receive, send)                      │ 
                           │   1055 │                                                                         │ 
                           │   1056 │   def add_api_route(                                                    │ 
                           │   1057 │   │   self,                                                             │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\applications.py:113 in __call__     │ 
                           │                                                                                  │ 
                           │   110 │   │   scope["app"] = self                                                │ 
                           │   111 │   │   if self.middleware_stack is None:                                  │ 
                           │   112 │   │   │   self.middleware_stack = self.build_middleware_stack()          │ 
                           │ ❱ 113 │   │   await self.middleware_stack(scope, receive, send)                  │ 
                           │   114 │                                                                          │ 
                           │   115 │   def on_event(self, event_type: str) -> typing.Callable:  # type: ignor │ 
                           │   116 │   │   return self.router.on_event(event_type)  # pragma: no cover        │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\errors.py:187 in         │ 
                           │ __call__                                                                         │ 
                           │                                                                                  │ 
                           │   184 │   │   │   # We always continue to raise the exception.                   │ 
                           │   185 │   │   │   # This allows servers to log the error, or allows test clients │ 
                           │   186 │   │   │   # to optionally raise the error within the test case.          │ 
                           │ ❱ 187 │   │   │   raise exc                                                      │ 
                           │   188 │                                                                          │ 
                           │   189 │   def format_line(self, index: int, line: str, frame_lineno: int, frame_ │ 
                           │       str:                                                                       │ 
                           │   190 │   │   values = {                                                         │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\errors.py:165 in         │ 
                           │ __call__                                                                         │ 
                           │                                                                                  │ 
                           │   162 │   │   │   await send(message)                                            │ 
                           │   163 │   │                                                                      │ 
                           │   164 │   │   try:                                                               │ 
                           │ ❱ 165 │   │   │   await self.app(scope, receive, _send)                          │ 
                           │   166 │   │   except Exception as exc:                                           │ 
                           │   167 │   │   │   request = Request(scope)                                       │ 
                           │   168 │   │   │   if self.debug:                                                 │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\sessions.py:85 in        │ 
                           │ __call__                                                                         │ 
                           │                                                                                  │ 
                           │   82 │   │   │   │   │   headers.append("Set-Cookie", header_value)              │ 
                           │   83 │   │   │   await send(message)                                             │ 
                           │   84 │   │                                                                       │ 
                           │ ❱ 85 │   │   await self.app(scope, receive, send_wrapper)                        │ 
                           │   86                                                                             │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\khoj\configure.py:332 in __call__             │ 
                           │                                                                                  │ 
                           │   329 │   │   async def __call__(self, scope: Scope, receive: Receive, send: Sen │ 
                           │   330 │   │   │   if scope["type"] == "http" and scope["path"].startswith("/_nex │ 
                           │   331 │   │   │   │   scope["path"] = "/static" + scope["path"]                  │ 
                           │ ❱ 332 │   │   │   await self.app(scope, receive, send)                           │ 
                           │   333 │   │                                                                      │ 
                           │   334 │   │   def __init__(self, app: ASGIApp) -> None:                          │ 
                           │   335 │   │   │   super().__init__(app)                                          │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\authentication.py:48 in  │ 
                           │ __call__                                                                         │ 
                           │                                                                                  │ 
                           │   45 │   │   if auth_result is None:                                             │ 
                           │   46 │   │   │   auth_result = AuthCredentials(), UnauthenticatedUser()          │ 
                           │   47 │   │   scope["auth"], scope["user"] = auth_result                          │ 
                           │ ❱ 48 │   │   await self.app(scope, receive, send)                                │ 
                           │   49 │                                                                           │ 
                           │   50 │   @staticmethod                                                           │ 
                           │   51 │   def default_on_error(conn: HTTPConnection, exc: Exception) -> Response: │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\base.py:188 in __call__  │ 
                           │                                                                                  │ 
                           │   185 │   │   with collapse_excgroups():                                         │ 
                           │   186 │   │   │   async with anyio.create_task_group() as task_group:            │ 
                           │   187 │   │   │   │   response = await self.dispatch_func(request, call_next)    │ 
                           │ ❱ 188 │   │   │   │   await response(scope, wrapped_receive, send)               │ 
                           │   189 │   │   │   │   response_sent.set()                                        │ 
                           │   190 │                                                                          │ 
                           │   191 │   async def dispatch(self, request: Request, call_next: RequestResponseE │ 
                           │       Response:                                                                  │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\base.py:222 in __call__  │ 
                           │                                                                                  │ 
                           │   219 │   │   │   }                                                              │ 
                           │   220 │   │   )                                                                  │ 
                           │   221 │   │                                                                      │ 
                           │ ❱ 222 │   │   async for chunk in self.body_iterator:                             │ 
                           │   223 │   │   │   await send({"type": "http.response.body", "body": chunk, "more │ 
                           │   224 │   │                                                                      │ 
                           │   225 │   │   await send({"type": "http.response.body", "body": b"", "more_body" │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\base.py:179 in           │ 
                           │ body_stream                                                                      │ 
                           │                                                                                  │ 
                           │   176 │   │   │   │   │   │   │   break                                          │ 
                           │   177 │   │   │   │                                                              │ 
                           │   178 │   │   │   │   if app_exc is not None:                                    │ 
                           │ ❱ 179 │   │   │   │   │   raise app_exc                                          │ 
                           │   180 │   │   │                                                                  │ 
                           │   181 │   │   │   response = _StreamingResponse(status_code=message["status"],   │ 
                           │       content=body_stream(), info=info)                                          │ 
                           │   182 │   │   │   response.raw_headers = message["headers"]                      │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\base.py:149 in coro      │ 
                           │                                                                                  │ 
                           │   146 │   │   │   │                                                              │ 
                           │   147 │   │   │   │   async with send_stream:                                    │ 
                           │   148 │   │   │   │   │   try:                                                   │ 
                           │ ❱ 149 │   │   │   │   │   │   await self.app(scope, receive_or_disconnect, send_ │ 
                           │   150 │   │   │   │   │   except Exception as exc:                               │ 
                           │   151 │   │   │   │   │   │   app_exc = exc                                      │ 
                           │   152                                                                            │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\sessions.py:85 in        │ 
                           │ __call__                                                                         │ 
                           │                                                                                  │ 
                           │   82 │   │   │   │   │   headers.append("Set-Cookie", header_value)              │ 
                           │   83 │   │   │   await send(message)                                             │ 
                           │   84 │   │                                                                       │ 
                           │ ❱ 85 │   │   await self.app(scope, receive, send_wrapper)                        │ 
                           │   86                                                                             │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\khoj\configure.py:332 in __call__             │ 
                           │                                                                                  │ 
                           │   329 │   │   async def __call__(self, scope: Scope, receive: Receive, send: Sen │ 
                           │   330 │   │   │   if scope["type"] == "http" and scope["path"].startswith("/_nex │ 
                           │   331 │   │   │   │   scope["path"] = "/static" + scope["path"]                  │ 
                           │ ❱ 332 │   │   │   await self.app(scope, receive, send)                           │ 
                           │   333 │   │                                                                      │ 
                           │   334 │   │   def __init__(self, app: ASGIApp) -> None:                          │ 
                           │   335 │   │   │   super().__init__(app)                                          │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\authentication.py:48 in  │ 
                           │ __call__                                                                         │ 
                           │                                                                                  │ 
                           │   45 │   │   if auth_result is None:                                             │ 
                           │   46 │   │   │   auth_result = AuthCredentials(), UnauthenticatedUser()          │ 
                           │   47 │   │   scope["auth"], scope["user"] = auth_result                          │ 
                           │ ❱ 48 │   │   await self.app(scope, receive, send)                                │ 
                           │   49 │                                                                           │ 
                           │   50 │   @staticmethod                                                           │ 
                           │   51 │   def default_on_error(conn: HTTPConnection, exc: Exception) -> Response: │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\base.py:188 in __call__  │ 
                           │                                                                                  │ 
                           │   185 │   │   with collapse_excgroups():                                         │ 
                           │   186 │   │   │   async with anyio.create_task_group() as task_group:            │ 
                           │   187 │   │   │   │   response = await self.dispatch_func(request, call_next)    │ 
                           │ ❱ 188 │   │   │   │   await response(scope, wrapped_receive, send)               │ 
                           │   189 │   │   │   │   response_sent.set()                                        │ 
                           │   190 │                                                                          │ 
                           │   191 │   async def dispatch(self, request: Request, call_next: RequestResponseE │ 
                           │       Response:                                                                  │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\base.py:222 in __call__  │ 
                           │                                                                                  │ 
                           │   219 │   │   │   }                                                              │ 
                           │   220 │   │   )                                                                  │ 
                           │   221 │   │                                                                      │ 
                           │ ❱ 222 │   │   async for chunk in self.body_iterator:                             │ 
                           │   223 │   │   │   await send({"type": "http.response.body", "body": chunk, "more │ 
                           │   224 │   │                                                                      │ 
                           │   225 │   │   await send({"type": "http.response.body", "body": b"", "more_body" │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\base.py:179 in           │ 
                           │ body_stream                                                                      │ 
                           │                                                                                  │ 
                           │   176 │   │   │   │   │   │   │   break                                          │ 
                           │   177 │   │   │   │                                                              │ 
                           │   178 │   │   │   │   if app_exc is not None:                                    │ 
                           │ ❱ 179 │   │   │   │   │   raise app_exc                                          │ 
                           │   180 │   │   │                                                                  │ 
                           │   181 │   │   │   response = _StreamingResponse(status_code=message["status"],   │ 
                           │       content=body_stream(), info=info)                                          │ 
                           │   182 │   │   │   response.raw_headers = message["headers"]                      │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\base.py:149 in coro      │ 
                           │                                                                                  │ 
                           │   146 │   │   │   │                                                              │ 
                           │   147 │   │   │   │   async with send_stream:                                    │ 
                           │   148 │   │   │   │   │   try:                                                   │ 
                           │ ❱ 149 │   │   │   │   │   │   await self.app(scope, receive_or_disconnect, send_ │ 
                           │   150 │   │   │   │   │   except Exception as exc:                               │ 
                           │   151 │   │   │   │   │   │   app_exc = exc                                      │ 
                           │   152                                                                            │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\cors.py:93 in __call__   │ 
                           │                                                                                  │ 
                           │    90 │   │   │   await response(scope, receive, send)                           │ 
                           │    91 │   │   │   return                                                         │ 
                           │    92 │   │                                                                      │ 
                           │ ❱  93 │   │   await self.simple_response(scope, receive, send, request_headers=h │ 
                           │    94 │                                                                          │ 
                           │    95 │   def is_allowed_origin(self, origin: str) -> bool:                      │ 
                           │    96 │   │   if self.allow_all_origins:                                         │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\cors.py:144 in           │ 
                           │ simple_response                                                                  │ 
                           │                                                                                  │ 
                           │   141 │                                                                          │ 
                           │   142 │   async def simple_response(self, scope: Scope, receive: Receive, send:  │ 
                           │       request_headers: Headers) -> None:                                         │ 
                           │   143 │   │   send = functools.partial(self.send, send=send, request_headers=req │ 
                           │ ❱ 144 │   │   await self.app(scope, receive, send)                               │ 
                           │   145 │                                                                          │ 
                           │   146 │   async def send(self, message: Message, send: Send, request_headers: He │ 
                           │       None:                                                                      │ 
                           │   147 │   │   if message["type"] != "http.response.start":                       │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\middleware\exceptions.py:62 in      │ 
                           │ __call__                                                                         │ 
                           │                                                                                  │ 
                           │   59 │   │   else:                                                               │ 
                           │   60 │   │   │   conn = WebSocket(scope, receive, send)                          │ 
                           │   61 │   │                                                                       │ 
                           │ ❱ 62 │   │   await wrap_app_handling_exceptions(self.app, conn)(scope, receive,  │ 
                           │   63 │                                                                           │ 
                           │   64 │   def http_exception(self, request: Request, exc: Exception) -> Response: │ 
                           │   65 │   │   assert isinstance(exc, HTTPException)                               │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\_exception_handler.py:53 in         │ 
                           │ wrapped_app                                                                      │ 
                           │                                                                                  │ 
                           │   50 │   │   │   │   handler = _lookup_exception_handler(exception_handlers, exc │ 
                           │   51 │   │   │                                                                   │ 
                           │   52 │   │   │   if handler is None:                                             │ 
                           │ ❱ 53 │   │   │   │   raise exc                                                   │ 
                           │   54 │   │   │                                                                   │ 
                           │   55 │   │   │   if response_started:                                            │ 
                           │   56 │   │   │   │   raise RuntimeError("Caught handled exception, but response  │ 
                           │      started.") from exc                                                         │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\_exception_handler.py:42 in         │ 
                           │ wrapped_app                                                                      │ 
                           │                                                                                  │ 
                           │   39 │   │   │   await send(message)                                             │ 
                           │   40 │   │                                                                       │ 
                           │   41 │   │   try:                                                                │ 
                           │ ❱ 42 │   │   │   await app(scope, receive, sender)                               │ 
                           │   43 │   │   except Exception as exc:                                            │ 
                           │   44 │   │   │   handler = None                                                  │ 
                           │   45                                                                             │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\routing.py:715 in __call__          │ 
                           │                                                                                  │ 
                           │   712 │   │   """                                                                │ 
                           │   713 │   │   The main entry point to the Router class.                          │ 
                           │   714 │   │   """                                                                │ 
                           │ ❱ 715 │   │   await self.middleware_stack(scope, receive, send)                  │ 
                           │   716 │                                                                          │ 
                           │   717 │   async def app(self, scope: Scope, receive: Receive, send: Send) -> Non │ 
                           │   718 │   │   assert scope["type"] in ("http", "websocket", "lifespan")          │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\routing.py:735 in app               │ 
                           │                                                                                  │ 
                           │   732 │   │   │   match, child_scope = route.matches(scope)                      │ 
                           │   733 │   │   │   if match == Match.FULL:                                        │ 
                           │   734 │   │   │   │   scope.update(child_scope)                                  │ 
                           │ ❱ 735 │   │   │   │   await route.handle(scope, receive, send)                   │ 
                           │   736 │   │   │   │   return                                                     │ 
                           │   737 │   │   │   elif match == Match.PARTIAL and partial is None:               │ 
                           │   738 │   │   │   │   partial = route                                            │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\routing.py:288 in handle            │ 
                           │                                                                                  │ 
                           │   285 │   │   │   │   response = PlainTextResponse("Method Not Allowed", status_ │ 
                           │       headers=headers)                                                           │ 
                           │   286 │   │   │   await response(scope, receive, send)                           │ 
                           │   287 │   │   else:                                                              │ 
                           │ ❱ 288 │   │   │   await self.app(scope, receive, send)                           │ 
                           │   289 │                                                                          │ 
                           │   290 │   def __eq__(self, other: typing.Any) -> bool:                           │ 
                           │   291 │   │   return (                                                           │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\routing.py:76 in app                │ 
                           │                                                                                  │ 
                           │    73 │   │   │   response = await f(request)                                    │ 
                           │    74 │   │   │   await response(scope, receive, send)                           │ 
                           │    75 │   │                                                                      │ 
                           │ ❱  76 │   │   await wrap_app_handling_exceptions(app, request)(scope, receive, s │ 
                           │    77 │                                                                          │ 
                           │    78 │   return app                                                             │ 
                           │    79                                                                            │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\_exception_handler.py:53 in         │ 
                           │ wrapped_app                                                                      │ 
                           │                                                                                  │ 
                           │   50 │   │   │   │   handler = _lookup_exception_handler(exception_handlers, exc │ 
                           │   51 │   │   │                                                                   │ 
                           │   52 │   │   │   if handler is None:                                             │ 
                           │ ❱ 53 │   │   │   │   raise exc                                                   │ 
                           │   54 │   │   │                                                                   │ 
                           │   55 │   │   │   if response_started:                                            │ 
                           │   56 │   │   │   │   raise RuntimeError("Caught handled exception, but response  │ 
                           │      started.") from exc                                                         │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\_exception_handler.py:42 in         │ 
                           │ wrapped_app                                                                      │ 
                           │                                                                                  │ 
                           │   39 │   │   │   await send(message)                                             │ 
                           │   40 │   │                                                                       │ 
                           │   41 │   │   try:                                                                │ 
                           │ ❱ 42 │   │   │   await app(scope, receive, sender)                               │ 
                           │   43 │   │   except Exception as exc:                                            │ 
                           │   44 │   │   │   handler = None                                                  │ 
                           │   45                                                                             │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\routing.py:74 in app                │ 
                           │                                                                                  │ 
                           │    71 │   │                                                                      │ 
                           │    72 │   │   async def app(scope: Scope, receive: Receive, send: Send) -> None: │ 
                           │    73 │   │   │   response = await f(request)                                    │ 
                           │ ❱  74 │   │   │   await response(scope, receive, send)                           │ 
                           │    75 │   │                                                                      │ 
                           │    76 │   │   await wrap_app_handling_exceptions(app, request)(scope, receive, s │ 
                           │    77                                                                            │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\responses.py:252 in __call__        │ 
                           │                                                                                  │ 
                           │   249 │   │   await send({"type": "http.response.body", "body": b"", "more_body" │ 
                           │   250 │                                                                          │ 
                           │   251 │   async def __call__(self, scope: Scope, receive: Receive, send: Send) - │ 
                           │ ❱ 252 │   │   async with anyio.create_task_group() as task_group:                │ 
                           │   253 │   │   │                                                                  │ 
                           │   254 │   │   │   async def wrap(func: typing.Callable[[], typing.Awaitable[None │ 
                           │   255 │   │   │   │   await func()                                               │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\anyio\_backends\_asyncio.py:597 in __aexit__  │ 
                           │                                                                                  │ 
                           │    594 │   │   │   │   else:                                                     │ 
                           │    595 │   │   │   │   │   raise ExceptionGroup(exceptions)                      │ 
                           │    596 │   │   │   elif exceptions and exceptions[0] is not exc_val:             │ 
                           │ ❱  597 │   │   │   │   raise exceptions[0]                                       │ 
                           │    598 │   │   except BaseException as exc:                                      │ 
                           │    599 │   │   │   # Clear the context here, as it can only be done in-flight.   │ 
                           │    600 │   │   │   # If the context is not cleared, it can result in recursive t │ 
                           │        #145).                                                                    │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\responses.py:255 in wrap            │ 
                           │                                                                                  │ 
                           │   252 │   │   async with anyio.create_task_group() as task_group:                │ 
                           │   253 │   │   │                                                                  │ 
                           │   254 │   │   │   async def wrap(func: typing.Callable[[], typing.Awaitable[None │ 
                           │ ❱ 255 │   │   │   │   await func()                                               │ 
                           │   256 │   │   │   │   task_group.cancel_scope.cancel()                           │ 
                           │   257 │   │   │                                                                  │ 
                           │   258 │   │   │   task_group.start_soon(wrap, partial(self.stream_response, send │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\starlette\responses.py:244 in stream_response │ 
                           │                                                                                  │ 
                           │   241 │   │   │   │   "headers": self.raw_headers,                               │ 
                           │   242 │   │   │   }                                                              │ 
                           │   243 │   │   )                                                                  │ 
                           │ ❱ 244 │   │   async for chunk in self.body_iterator:                             │ 
                           │   245 │   │   │   if not isinstance(chunk, (bytes, memoryview)):                 │ 
                           │   246 │   │   │   │   chunk = chunk.encode(self.charset)                         │ 
                           │   247 │   │   │   await send({"type": "http.response.body", "body": chunk, "more │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\khoj\routers\api_chat.py:693 in               │ 
                           │ event_generator                                                                  │ 
                           │                                                                                  │ 
                           │    690 │   │   │   await conversation.asave()                                    │ 
                           │    691 │   │   │   agent = default_agent                                         │ 
                           │    692 │   │                                                                     │ 
                           │ ❱  693 │   │   await is_ready_to_chat(user)                                      │ 
                           │    694 │   │   user_name = await aget_user_name(user)                            │ 
                           │    695 │   │   location = None                                                   │ 
                           │    696 │   │   if city or region or country or country_code:                     │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\khoj\routers\helpers.py:150 in                │ 
                           │ is_ready_to_chat                                                                 │ 
                           │                                                                                  │ 
                           │    147 │   │   max_tokens = user_conversation_config.max_prompt_size             │ 
                           │    148 │   │   if state.offline_chat_processor_config is None:                   │ 
                           │    149 │   │   │   logger.info("Loading Offline Chat Model...")                  │ 
                           │ ❱  150 │   │   │   state.offline_chat_processor_config = OfflineChatProcessorMod │ 
                           │        max_tokens)                                                               │ 
                           │    151 │   │   return True                                                       │ 
                           │    152 │                                                                         │ 
                           │    153 │   if (                                                                  │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\khoj\utils\config.py:81 in __init__           │ 
                           │                                                                                  │ 
                           │   78 │   │   except ValueError as e:                                             │ 
                           │   79 │   │   │   self.loaded_model = None                                        │ 
                           │   80 │   │   │   logger.error(f"Error while loading offline chat model: {e}", ex │ 
                           │ ❱ 81 │   │   │   raise e                                                         │ 
                           │   82                                                                             │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\khoj\utils\config.py:77 in __init__           │ 
                           │                                                                                  │ 
                           │   74 │   │   self.chat_model = chat_model                                        │ 
                           │   75 │   │   self.loaded_model = None                                            │ 
                           │   76 │   │   try:                                                                │ 
                           │ ❱ 77 │   │   │   self.loaded_model = download_model(self.chat_model, max_tokens= │ 
                           │   78 │   │   except ValueError as e:                                             │ 
                           │   79 │   │   │   self.loaded_model = None                                        │ 
                           │   80 │   │   │   logger.error(f"Error while loading offline chat model: {e}", ex │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\khoj\processor\conversation\offline\utils.py: │ 
                           │ 31 in download_model                                                             │ 
                           │                                                                                  │ 
                           │   28 │   │   kwargs["chat_format"] = "gemma"                                     │ 
                           │   29 │                                                                           │ 
                           │   30 │   # Check if the model is already downloaded                              │ 
                           │ ❱ 31 │   model_path = load_model_from_cache(repo_id, filename)                   │ 
                           │   32 │   chat_model = None                                                       │ 
                           │   33 │   try:                                                                    │ 
                           │   34 │   │   chat_model = load_model(model_path, repo_id, filename, kwargs)      │ 
                           │                                                                                  │ 
                           │ E:\GPT\khoj\khoj\Lib\site-packages\khoj\processor\conversation\offline\utils.py: │ 
                           │ 63 in load_model_from_cache                                                      │ 
                           │                                                                                  │ 
                           │   60                                                                             │ 
                           │   61 def load_model_from_cache(repo_id: str, filename: str, repo_type="models"): │ 
                           │   62 │   # Construct the path to the model file in the cache directory           │ 
                           │ ❱ 63 │   repo_org, repo_name = repo_id.split("/")                                │ 
                           │   64 │   object_id = "--".join([repo_type, repo_org, repo_name])                 │ 
                           │   65 │   model_path = os.path.sep.join([HF_HUB_CACHE, object_id, "snapshots", "* │ 
                           │      filename])                                                                  │ 
                           │   66                                                                             │ 
                           ╰──────────────────────────────────────────────────────────────────────────────────╯ 
                           ValueError: not enough values to unpack (expected 2, got 1)
[19:39:16.183901] INFO     uvicorn.access: 127.0.0.1:53688 - "GET /api/chat/sessions HTTP/1.1" 200

**Comment by debanjum** [comment]
Hey @YIRU69 , what is the format in which you've added the model name? And did you go through the first run experience where Khoj ask which chat models to use? It usually sets up llama3.x 8b as on one of the default models available, in which case you just have to select it on the settings page at http://localhost:42110/settings. 

You need to use HuggingFace repo name format of <person/org>/<model_name> to add your models of choice.
For example, to use llama-3.1 8b you can add something like [bartowski/Meta-Llama-3.1-8B-Instruct-GGUF](https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF). You can find chat models and their names on [HuggingFace](https://huggingface.co/models?library=gguf)

**Comment by YIRU69** [comment]
Thank you, I will try it later again. 
But I add the model name. [bartowski/Meta-Llama-3.1-8B-Instruct-GGUF](https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF) 
It also can't work.

**Comment by YIRU69** [comment]
@debanjum Hi, I set it. But it also don't work.
![image](https://github.com/user-attachments/assets/9856c395-3291-404f-ac84-c991060ef73a)

![image](https://github.com/user-attachments/assets/0a46e03d-15d1-4bf5-b7bb-4e64f16f9bc8)

![image](https://github.com/user-attachments/assets/15481b48-42e7-4374-80a9-609da56043d7)

![image](https://github.com/user-attachments/assets/5c84a2ca-6f51-4ed6-a058-d56edee8f2e4)

**Comment by YIRU69** [comment]
Update: It should add the openai config.

**Comment by debanjum** [comment]
Ok, there's been some confusion. Let's clear it up. There are multiple ways to use local chat models with Khoj. Based on the discussion on Discord it seems you may have been trying to setup Khoj to use a local chat model with Ollama? If so see the docs to [setup Khoj with Ollama](https://docs.khoj.dev/advanced/ollama) for the most accurate instructions. In general though:

## For Ollama
1. You should set the chat model name to whichever chat model you're running on ollama. E.g `llama3.1:8b`
2. You should set an OpenAI Processor Config that points OpenAI server URL to your Ollama server in the ChatModelOptions
3. You should set the ModelType to OpenAI. (This is because Ollama expose an OpenAI API compatible server that Khoj uses to interact with Ollama chat models)

## For Direct
1. You should set the chat model name to the  `bartowski/Meta-Llama-3.1-8B-Instruct-GGUF`
2. You set the ModelType to `Offline`
3. You *do not* set the OpenAI processor in the ChatModelOption as it is not used.

Khoj will download that chat model and run it directly without using any service/api like Ollama.

**Comment by debanjum** [comment]
> ![image](https://github.com/user-attachments/assets/90d8f4c9-99de-4d40-a344-4d597e731b1d)

Specifically this config should either set chat model field to `llama3.1:8b` to use with your ollama setup or set model type to offline and unset openai config field to load the model directly in Khoj but **not do both**

**Comment by YIRU69** [comment]
Thank you, I will try it again.

**Comment by YIRU69** [comment]
It worked! Thanks!
