### ISSUE TITLE
[FIX]cannot log in to  django adminstration 

### ISSUE THREAD

**Issue by bookandlover** [khoj-ai/khoj#986]
## Describe the bug
The latest Mac os with docker and docker-compose.yaml setup done. Run well but not login to the django admin. Try some usernames with the password set in yaml file.
<img width="646" alt="image" src="https://github.com/user-attachments/assets/4c2ad910-b246-4cb0-b162-f808bf025235">

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [ ] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

**Comment by bookandlover** [comment]
Solved and thanks. Delete the old image and reinstall. Working now. Seems I edited the username and password after running khoj. The  project is the best one I have ever seen.

**Comment by dariusbdockery** [comment]
I am unfortunately having the same problem. 

# Steps Taken
1. I installed using docker-compose and followed the steps in the documentation. 
2. I came to this ticket and then went back and deleted the containers and images and reinstalled with my credentials filled in from the start. I still couldn't access the admin panel and got the same error.
4. I also saw the following output from the server and thought it might be registering the default config for some reason, so I tried using them from the original docker-compose.yaml file, but still got the same error upon logging in:
![image](https://github.com/user-attachments/assets/f55c5583-63c0-4d13-93bc-b0b1d2f4078b)

# Possible Related Issue
After installing via docker-compose, Khoj launches fine, but I see no models available to me via the web interface (running latest Firefox and tried on Chrome) despite configuring it to use Ollama. 
![image](https://github.com/user-attachments/assets/bebad63e-4ea0-4c6e-99d2-d22a6592bf01)

I am not sure if my install is completely broken, or if the two are related, but any help would be great.

**Comment by sabaimran** [comment]
@dariusbdockery , what happens when you try to go to the `http://localhost:42110/server/admin` page? Are you also getting a login error, or something else?

**Comment by dariusbdockery** [comment]
@sabaimran, Yes I get the same login error as `bookandlover` above--even with default variables in the docker-compose file:

![image](https://github.com/user-attachments/assets/1edcc2c4-b33c-4203-b2d8-c1756bbb2165)

**Comment by debanjum** [comment]
> Yes I get the same login error as bookandlover above--even with default variables in the docker-compose file:

Hey @dariusbdockery that's unfortunate (and confusing). Can you delete the `khoj_khoj_db` docker volume, restart khoj  (i.e `docker-compose up`) and see if you can now login to the admin portal at http://localhost:42110/server/admin using the `KHOJ_ADMIN_EMAIL` and `KHOJ_ADMIN_PASSWORD` set in your `docker-compose.yml`? This is similar to what bookandlover did to solve their admin login issues.

### For context:
The Khoj admin user is created on first run of Khoj on your machine and persisted via a docker volume across Khoj service restarts. To change your Khoj admin user email, password in the docker-compose.yml **after** the first run, you should delete the Khoj db docker volume first and then restart the khoj service to recreate it with the latest credentials in your `docker-compose.yml` file.

See screenshot of deleting the khoj db docker volume via the Docker desktop app below:

<img width="1265" alt="Screenshot 2024-12-15 at 12 18 08" src="https://github.com/user-attachments/assets/7cf6e261-2dec-4d42-a220-722e8f1018b0" />
