### ISSUE TITLE
[FIX] Cannot use online search using Olostep + generate chart like example

### ISSUE THREAD

**Issue by alaireselene** [khoj-ai/khoj#990]
## Describe the bug
I've setup the API, and try to ask it some information from online source with default agent, but it cannot. The API works normally.

## To Reproduce
Prompt 1: Search for latest web framework news today.
Prompt 2: create a chart comparing the number of people in each continent. use a bar chart.

## Screenshots
![image](https://github.com/user-attachments/assets/d1b73b92-a66f-4fc0-9057-1a9506e4ea3a)
![image](https://github.com/user-attachments/assets/dc58f0a4-a8e8-42ca-b033-e5d907875ba7)

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [x] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [x] Web browser
    - [ ] WhatsApp
- OS:
    - [x] Windows
    - [ ] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version: 1.30.7

## Additional context
No.

**Comment by sabaimran** [comment]
1. You'll also have to setup [Jina](https://jina.ai/) or [Serper](https://serper.dev/) for running the Google searches. Jina also has the benefit that you can use it for both web searching and scraping, though the speeds are a bit slow. Nevertheless, mostly good enough. 
2. Which model are you using? Since you're using Docker, it should have automatically setup the code execution sandbox in the background, but it seems like the model didn't correctly decide to use the `code` tool.

**Comment by alaireselene** [comment]
I just use OpenAPI 4o-mini. So I need to fill in all 3 searching APIs?
Btw, AnythingLLM have an option to use Google Search API directly, you can consider about it.

**Comment by sabaimran** [comment]
You don't have to use all three. I recommend using just https://serper.dev

Olostep and Jina are not required. 

Will look into direct Google search!

**Comment by alaireselene** [comment]
Yeah, I'll try that and see if it works.
Here is [Google Custom Search API](https://developers.google.com/custom-search/v1/overview?hl=en), with 100 queries/user per day. Or [Bing Search API](https://www.microsoft.com/en-us/bing/apis/pricing), 3 queries/s, 1k queries/month. It is good enough to find anything that no need to read the whole page content, like research paper.
